generator/operation.go
I found that when I used -target, I was still getting restapi stuff ditched into my gopath.
I believe the fix below covers that issue.
=> Fix -target path injected at end of operations instead of beginning

generator/support.go, generator/templates/server/main.gotmpl
Hi, with these changes we are able to compile and run the server that get generated.
The first change changes `swagger` to `httpkit` because httpkit is the right import.
The second change is to move the private function `configureAPI` to main.gotmpl because being in configureapi.gotmpl doesn't make it visible to the main.gotmpl. We realized that they are both in the same package `main` but it is not visible, but moving the function to the main.gotmpl makes it work.
Maybe it is because the package folder is different but it is not clear. 
If you would rather have different PRs, please let us know and we will resubmit.
Thanks.
=> fix support.go known Consumers/Producers and configureApi func

generator/operation.go, generator/support.go
The package handling code currently assumes that the path separator is the slash, and also that Go package paths and file paths use the same separator. This PR has small fixes go make it work on Windows but I wonder if there is some better way (e.g. something from go/build) to handle the imports.
=> Fix package path handling on Windows

internal/validate/spec.go, internal/validate/spec_test.go
This improvement in error reporting will help to diagnose path parameter validation errors, but also bugs in go-swagger itself such as #63.
=> validation: show path in path parameter validation errors

generator/client.go
I found that the `package` was not being set correctly when generating the client code. Digging into things, I saw that `operation.Package` wasn't getting a value from the options.
There might be a better way to fix this or it's possible I'm doing something wrong when generating the client code.
=> Ensure operation.Package has a value.

httpkit/middleware/context.go
201 Responses should be able to contain a body. There is no rule enforcing HTTP 201 status code to return an empty body. The current code does not allow a 201 response to contain a body.
According to HTTP 1.1 spec:
>201 Created
>The request has been fulfilled and resulted in a new resource being created. The newly created resource can be referenced by the URI(s) returned in the entity of the response, with the most specific URI for the resource given by a Location header field. The response SHOULD include an entity containing a list of resource characteristics and location(s) from which the user or user agent can choose the one most appropriate. The entity format is specified by the media type given in the Content-Type header field. The origin server MUST create the resource before …
=> Allow http status 201 to have a response body

fixtures/codegen/todolist.simple.yml, generator/bindata.go, generator/operation.go, generator/operation_test.go, generator/templates/server/responses.gotmpl
New response objects should be created with `NewXXXX()` function call
instead of `XXXX{}` struct instantiation. Then default values for
headers will be pre filled.
Signed-off-by: Aleksandr Vinokurov <aleksandr.vin@gmail.com>
=> Add default value support for response headers, fixes #172

strfmt/time.go, strfmt/time_test.go
* Tests in strfmt/time_test.go were separated to logical groups
* Excessive tests were removed
* Some assertions were normalized
* strfmt.NewDateTime function was added to represent zero value for DateTime
* strfmt.DateTime UnmarshalText was reduced, delegating decision to ParseDateTime
=> Refactor strfmt/time tests, add strfmt.NewDateTime function

httpkit/middleware/request_test.go, httpkit/middleware/string_conversion_test.go, httpkit/middleware/untyped_request_test.go, strfmt/date.go, strfmt/date_test.go, strfmt/time.go, strfmt/time_test.go
Make consistent to strfmt.Duration type.
Closes #205.
Signed-off-by: Aleksandr Vinokurov <aleksandr.vin@gmail.com>
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/go-swagger/go-swagger/pull/206%23issuecomment-171106285%22%2C%20%22https%3A//github.com/go-swagger/go-swagger/pull/206%23issuecomment-171106395%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/go-swagger/go-swagger/pull/206%23issuecomment-171106285%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22After%20adding%20missed%20fixes%20to%20tests%2C%20all%20seems%20to%20be%20ok%22%2C%20%22created_at%22%3A%20%222016-01-13T00%3A08%3A59Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/ …
=> Change strfmt.DateTime and strfmt.Date types to alias

generator/support.go
- Before, operations without a "Tag" field in their spec would
generate incorrect imports (`$PROJECT/restapi/operations/operations`
instead of `$PROJECT/restapi/operations`)
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/casualjim%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/go-swagger/go-swagger/pull/209%23issuecomment-171498933%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-01-14T01%3A48%3A33Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%2C%20%22html_url%22%3A%2 …
=> Fix import path for operations that lack tags

cmd/swagger/commands/generate/server.go, generator/shared.go, generator/support.go
- The comment for the server main template says that main should only be
overwritten if an `--include-main` flag is passed to `swagger
generate`.  This adds that flag and enforces it.
Fixes https://github.com/go-swagger/go-swagger/issues/210
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/casualjim%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/go-swagger/go-swagger/pull/211%23issuecomment-171517110%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-01-14T03%3A10%3A28Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatar …
=> skip generating server main if it exists:

generator/templates/server/parameter.gotmpl
request.ParseMultipartForm will return an error if the Content-Type is wrong. If the Content-Type is not a multipart this will just call ParseForm instead.
=> Fixes #263.

scan/scanner.go, scan/scanner_test.go
Any feedback is appreciated, and please let me know if special mark-up is not supposed to work.
Fixes #276.
=> scan: strip only special chars that are used in annotations

httpkit/client/runtime.go, httpkit/client/runtime_test.go
Given a path like "/api/tasks/" the runtime uses `path.Join` to join the
base path to it which strips any trailing slash. If the path previously
ended with a trailing slash ("/"), it is reinstated after adding the
base path prefix because the behaviour of the server's path handling
cannot be guaranteed.
Fixes #289
Signed-off-by: Jonathan Ingram <jonathan.b.ingram@gmail.com>
=> Preserve trailing slash in URL path in runtime

generator/templates/client/parameter.gotmpl
The generated code does not compile if a file parameter has the property "required": true.
For example:
`"parameters": [
{
"name": "file",
"in": "formData",
"description": "file to upload",
"required": true,
"type": "file"
}
],
"consumes": [
"multipart/form-data"
],`
=> fix file type parameter when the parameter is required

httpkit/client/runtime.go, httpkit/client/runtime_test.go
Adds support for setting the `http.CookieJar` to `httpkit/client/runtime.go`, similar to the existing support for setting the `http.RoundTripper`. The default jar is nil as before (no support for cookies). Fixes #308.
=> Add support for cookies in the client runtime

generator/model.go
Add the missing import:
github.com/go-swagger/go-swagger/httpkit
To fix #343
=> fix missing httpkit import in models

generator/support.go, httpkit/client/request_test.go, httpkit/client/runtime.go, httpkit/client/runtime_test.go, httpkit/constants.go, httpkit/text.go, httpkit/text_test.go
Add plain text consumer and producer and use it in client runtime and generator support. Fixes #360.
=> Add plain text consumer and producer

cmd/swagger/commands/generate/model.go
In command `generate model ...`, It's not necessary to force `--name` as required. If we don't specify a name, it should generate all models.
=> generate all models if name not specified

httpkit/middleware/validation.go
If allowed list is empty, it means it doesn't matter which content type it is.
=> Allow empty content-type when allowed list is empty

generator/support.go
Added a mapping for application/.*raw-stream to bin mapping for
mimetypes.  We have a specific vendor mimetype that ends in
raw-stream that we would like to get handle.  If this isn't there,
we can get a panic during runtime in some code generation.  If
the generated file restapi/operations/xxx_api.go refers to the
mimetype as the defaultConsumes or defaultProduces, our server
will panic.  Adding this resolves the panic.
=> Add *raw-stream mimetype mapping

scan/schema.go
Error messages improved. By example:
Old message is:
&{%!s(token.Pos=1478849) %!s(*ast.FieldList=&{1478853 [0xc8217db440] 1478870}) %!s(*ast.FieldList=&{1478872 [0xc8217db480 0xc8217db4c0] 1478888})} is unsupported for a schema
New message is:
Expr (/path/src/gopkg.in/mgo.v2/session.go:386:13) is unsupported for a schema
=> Improve error message

httpkit/client/runtime.go
The functionality to determine the value of reinstateSlash would
set it to true in the case where req.URL.Path is "/".  This would
result in an extra "/" being appended to req.URL.Path after it was
joined with the BasePath, causing requests to fail.  The path.Join()
function calls path.Clean() on each path element to be joined.
Clean() will return a trailing "/" on a path element only if it is
"/".
=> Fixed bug in httpkit/client/runtime.go Submit()

fixtures/goparsing/classification/operations/todo_operation.go, scan/routes_test.go, scan/scanner.go, scan/validators.go
This PR aims to fix:  https://github.com/go-swagger/go-swagger/issues/449
I changed the `/fixtures/goparsing/classification/operations/todo_operation.go` file in order to test more general scopes (For example Google uses URL as scopes).
I changed the  `scan/routes_test.go` accordingly.
I removed the useless regexp that I replaced with a simple TrimAfter followed by a TrimSpace. This is possibile because following the specifications scopes can't contain spaces (must be url encoded if present).
Signed-off-by: Paolo Galeone <nessuno@nerdz.eu>
=> Fix https://github.com/go-swagger/go-swagger/issues/449

generator/pointer_test.go, generator/types.go
This change introduces a precedence for a user defined attribute x-nullable.
x-nullable is an extension that actually gives user a freedom to optionally define code generator behavior for nullable and non nullable values.
=> X nullable first

generator/discriminators_test.go, generator/model.go
For some reason the schema for array item is enforced in such way that array items become required.
I created a copy of the originating schema and reset required flag for it. Test update was necessary.
=> Required flag is reset for array items.

generator/templates/server/parameter.gotmpl
=> Use canonicalized keys to retrieve values from http.Request.Header

fixtures/goparsing/bookings/api.go, scan/scanner.go, scan/scanner_test.go, scan/schema.go
When parsing discovered schemas it includes all structs including ones that should not be included. This patch makes the schemaParser aware of the discovered schema so we can use that information to exclude schema that are not needed.
=> Prevents parsing structs that are needed when parsing dicovered schemas

fixtures/goparsing/classification/operations/noparams.go, scan/parameters.go
Signed-off-by: Jake Burkhead <jake.b@socialcodeinc.com>
relates to https://github.com/go-swagger/go-swagger/issues/520
=> skip fields in parameter structs with struct tag `json:"-"`

fixtures/goparsing/classification/models/nomodel.go, scan/scanner.go, scan/schema_test.go
* added support for byte, uintptr
* added error for complex64, complex128, there's no default JSON
marshaller
* changed rune from string to int32 according to Go docs
=> Fix issue #560 Go builtin support

fixtures/goparsing/classification/models/nomodel.go, scan/schema.go, scan/schema_test.go
Any suggestions on how to test this? Seems like the test in scan/classifier_test.go are similar, maybe add model with embedded pointer in fixtures/goparsing/classification/models/ ? Didn't find an example that would test whether the JSON model  is correct (e.g. we want the embedded type to be there as optional).
The committed change produces correct  swagger, as far as I can tell, i.e. the members of embedded type are all there and optional.
=> Fix issue #563 Added StarExpr in parseEmbeddedType

examples/tutorials/todo-list/server-complete/restapi/configure_todo_list.go
Within the `server-complete` example code, show how someone would use the facilities for adding command line flags.
Closes #572 
Signed-off-by: Nelson Carpentier <nelz9999@gmail.com>
=> Command Line Flags Example

generator/templates/server/server.gotmpl
We would like to propose exposing the server handler via a getter so that we can use the handler in test suites. See below for an example use case:
```go
package apitests
import (
"io"
"log"
"net/http/httptest"
"github.com/go-openapi/loads"
"github.com/xiwenc/someService/restapi"
"github.com/xiwenc/someService/restapi/operations"
)
var testserver *httptest.Server
func setup() {
swaggerSpec, err := loads.Analyzed(restapi.SwaggerJSON, "")
if err != nil {
log.Fatalln(err)
}
api := operations.ExampleServiceAPI(swaggerSpec)
server := restapi.NewServer(api)
server.ConfigureAPI()
testserver = httptest.NewServer(server.GetHandler()) // The proposed change would enable easier usage of the handler in tests
}
func teardown() {
testserver.Close()
}
func TestSample(t *testing.T) {
setup()
// do some …
```
=> Expose server handler which can be used for writing tests

fixtures/goparsing/classification/operations_body/todo_operation_body.go, scan/routes_test.go, scan/validators.go
Example:
``` 
//swagger:model Person
// swagger:route GET /person/{id} people getPerson
//
// Get the person by id.
//
// Returns a person
//
// Consumes:
// - application/json
//
// Produces:
// - application/json
//
// Schemes: https
//
// Responses:
//     200: body:Person
```
Properly uses a person from a schema defined with the swagger spec when using generate spec.
Closes #595
Closes #140
=> Add the ability to use a model as a response.

fixtures/goparsing/classification/models/nomodel.go, scan/schema.go, scan/schema_test.go
For example, this should use the name "Foo" rather than the blank string:
Foo string `json:",omitempty"`
=> Support json tags which don't set name

scan/routes_test.go, scan/validators.go
* According to the Security Object Requirements[1] for "other security
scheme types, the array MUST be empty." Initializing the scopes
slice fixes this issue by no longer returing "null" in the json.
This also works for the case of oauth as the security type since
that is expecting an array of scopes.
[1] http://swagger.io/specification/#securityRequirementObject
Signed-off-by: Harley Laue <losinggeneration@gmail.com>
=> Fix scopes to be initialized to an empty array

scan/schema.go
issue with parsing custom types for maps
```go
type MapType map[string]string
type MapTypeArr map[string][]string
type MyStruct struct {
Field   MapType
Field2   MapTypeArr
}
```
I have problem with writing test for it fast, just have to spend more time to understand what is going on there and create the test.
Looks like there is one issue more, but i didn't find it yet.
example is here: 
https://github.com/gaplyk/go-swagger-issue
=> fix issue with map type

fixtures/goparsing/classification/models/extranomodel.go, fixtures/goparsing/classification/models/nomodel.go, scan/schema.go, scan/schema_test.go
issue with parsing custom types for maps
```go
type MapType map[string]string
type MapTypeArr map[string][]string
type MyStruct struct {
Field   MapType
Field2   MapTypeArr
}
```
I have problem with writing test for it fast, just have to spend more time to understand what is going on there and create the test.
Looks like there is one issue more, but i didn't find it yet.
example is here: 
https://github.com/gaplyk/go-swagger-issue
=> Tests for issue with maps

examples/task-tracker/client/tasks/add_comment_to_task_responses.go, examples/task-tracker/client/tasks/create_task_responses.go, examples/task-tracker/client/tasks/delete_task_responses.go, examples/task-tracker/client/tasks/get_task_comments_responses.go, examples/task-tracker/client/tasks/get_task_details_responses.go, examples/task-tracker/client/tasks/list_tasks_responses.go, examples/task-tracker/client/tasks/update_task_responses.go, examples/task-tracker/client/tasks/upload_task_file_responses.go, examples/todo-list/client/todos/add_one_responses.go, examples/todo-list/client/todos/destroy_one_responses.go, examples/todo-list/client/todos/find_responses.go, examples/todo-list/client/todos/update_one_responses.go, generator/templates/client/response.gotmpl, vendor/github.com/asaskevich/govalidator/validator.go
Spotted that the code had 'recieved' in it, both in templates and comments. This patch changes that to 'received'
=> Correcting typo

generator/templates/server/server.gotmpl
Hi,
I found the following problem: if I will run the server with `--host=0.0.0.0` and I have both http and https schemes - the server will panic with `listen tcp: too many colons in address :::0`.
I think I figured out what's going wrong:
1. here https://github.com/go-swagger/go-swagger/blob/master/generator/templates/server/server.gotmpl#L230 `s.Host` is being used to construct the address. This works fine.
2. here https://github.com/go-swagger/go-swagger/blob/master/generator/templates/server/server.gotmpl#L239 `s.Host` will be re-assigned with the value from the `swag.SplitHostPort(listener.Addr().String())`. This works mostly fine except when the host is `0.0.0.0`. In this case `s.Host` will be `::` which apparently would mean all interfaces.
3. and finally here …
=> Default https host before mutating it.

cmd/swagger/commands/generate/operation.go, generator/operation.go
Fixes #676
* adds `--skip-validator` to `swagger generate operation` so that models can be generated without validation
* fixes a bug where anonymous response objects were created with a suffix of `BodyBody`. Now only one `Body` as appended
* adds support for setting the name of an anonymous schema from the `title`
If any of this is controversial I'd be happy to split it into a separate PR to get the rest merged.
=> Bug fixes for generating operation models

generator/typeresolver_test.go, generator/types.go
Re discussion in slack (https://goswagger.slack.com/archives/general/p1475701532000329)
`false` values for `x-nullable` were being ignored. This allows nested models to be non-pointers.
=> Allow x-nullable for nested models

scan/schema.go
of properties when allOf is exists in the struct
example: 
```go 
type EmbeddedModel struct {
Field string `json:"field"`
}
type AllOfStruct struct {
// swagger:allOf
EmbeddedModel
}
````
the result gonna be:
```json
"AllOfStruct":{
"allOf":[
{"type":"object","properties":{"field":{"type":"string","x-go-name":"Field"}}},
{"type":"object"}
]
}
```
=> Fix issue with empty schema 

generator/model.go, generator/operation.go, generator/types.go
Fixes #701 
Fixes #402 
The second commit is reverting one of my earlier changes. I didn't realize that `x-go-name` was the correct way to set the name of the model. Trying to set the name from a title will probably break things.
=> Support x-go-name in code generation

fixtures/goparsing/classification/operations/noparams.go, scan/parameters.go, scan/parameters_test.go
Pulls the simple loop out in favor of a recursive function to handle `ast.StarExpr`. This does not extend to something like
```go
// swagger:parameters fooBar
type FooBarParams struct {
// Other things
Other []*[]struct {
Those string `json:"those"`
} `json:"other"`
}
```
but I assumed that would be ok as I can't see a real use for that construct.
=> Adds support for parsing `[]*Foo` in parameters

scan/parameters.go, scan/parameters_test.go
Ensure that parameters scanner maintains the sequence of the parameters, as it is in the code.
closes #768
=> fixed parameters sequence issue

generator/templates/header.gotmpl, generator/templates/schemavalidator.gotmpl, generator/templates/server/parameter.gotmpl
fix the problem: 
when a pattern validation fails on a field in request body, which is a type definition referencing to another definition, the returned error message won't show the validation failed field name, causing trouble to read what field failed at validation.
=> fix #767: field-name-not-showing-if-using-ref

generator/templates/schemavalidator.gotmpl
Problem:
Go-swagger supports array type validation for the modals that uses direct definition, while if the modal definition is set by $ref (aliased), the validation logic are not generated in Swagger templates rendering, causing Rest server unable to prevent invalid rest calls.
Fix:
By allowing `IsAliased` items to be rendered for type validation.
=> fix 805-support-array-type-validation-for-aliased-definition

generator/model.go, generator/structs.go, generator/templates/schema.gotmpl
If there is another place able to pull the defaults without introducing a new `Default` field in `GenSchema` (and feeding into the templates), the following would be revised.
=> 828-Support-default-value-for-model-property

generator/bindata.go, generator/templates/client/facade.gotmpl
Fixes issue #838.
> Create a client with a custom httpTransport, without having to hardcode the basePath, host and schemes;
This is now possible by using the constants provided by the client package: `DefaultHost`, `DefaultBasePath` and `DefaultSchemes`.
> Create a client with all defaults, except 1 customized one (e.g. a custom host, as is often required for public API's);
This is now possible by calling `NewHTTPClientWithConfig` instead of `NewHTTPClient`:
```go
NewHTTPClientWithConfig(nil, DefaultTransportConfig().WithHost("http://localhost:9000"))
```
Logic from `NewHTTPClient` has been moved to `NewHTTPClientWithConfig`. `NewHTTPClient` calls `NewHTTPClientWithConfig` now, with a nil value for the config value, making it default via `DefaultTransportConfig`.
=> expose transport config, fixes #838

fixtures/bugs/846/swagger.yml, generator/operation.go, generator/response_test.go
fixes #846
Also added a unit test to ensure the order of the Response & Body (payload).
Using a new swagger build with these changes, it now seems to appear that the order of generated objects is constant across sequential generations. Tested it for both the client and server of the EVE API Spec referenced in #846. Locally it seems to hold up, as it seemed to be only the body (extraSchemes) that were not sorted yet. Therefore I only added a unit-test to test the order of the body, as mentioned earlier.
=> ensure constant client response body order

generator/bindata.go, generator/support.go, generator/templates/swagger_json_embed.gotmpl
embeded_spec.go file contains swagger spec as an array of bytes that is not readable and not really diffable in case of the original swagger spec change. This PR addresses this by representing swagger spec as a string.
=> Generate code that keeps swagger spec as a string instead of a []byte

docs/use/template_layout.md, generator/shared.go
As per #894 - allowing skipping of FormatContent behaviour when dealing with non-golang code output.
=> Allow CodeGen to skip formatting

docs/tutorial/custom-server.md
Fixes #889 
Note that I in the end opted for building a super simple server, as the kvstore had in my opinion way to much details that would distract the reader of this tutorial. The actual goal of this tutorial is to teach users new to go-swagger how to build a server, with a custom defined cli and hand-written handlers.
The tutorial does reference the kvstore example twice. Especially in the end we want to make clear that the server we created in this tutorial is very simple, and that the user might want to check out the kvstore example next to see a more complex example, built using the exact same techniques as showcases in this tutorial.
For now I've stored the end result of the tutorial as https://github.com/GlenDC/custom-swagger-server but in case you want it to be under the …
=> add custom server tutorial

generator/types.go
fixes #875 
Original fix was actually resolving the TODO, but then I realized the function is no longer used, so I am proposing to delete it instead. Git History always has it in case you ever want to revive it again somewhere in the future.
=> remove unused resolveSimpleType func

fixtures/specs/response_name.json, generator/operation.go, generator/response_test.go, vendor/github.com/go-openapi/spec/response.go, vendor/manifest
The Go name for response types is currently always derived from the HTTP
status code description. Add an optional vendor extension 'x-go-name'
to overwrite the name used for Go code generation.
Example:
```
paths:
"/testing":
put:
responses:
400:
description: Missing element in request
x-go-name: Missing
```
Will result in:
```
const PutTestingMissingCode int = 400
type PutTestingMissing struct {
}
func NewPutTestingMissing() *PutTestingMissing {
return &PutTestingMissing{}
}
```
=> Support x-go-name in response elements

cmd/swagger/commands/serve.go
The body of this `if` statement only reassigns the same value that was already assigned from; the value of `basePath` will still be the empty string afterwards, in all cases where the `if`-block actually executes.
=> Remove no-op basePath assignment.

scan/parameters.go, scan/schema.go
1. Package lookup
for imports like `github.com/name/my-name-of-project` which has package name `name`
2. Added ast.SelectorType
```go
type Str struct {
List []*pkg.Field
}
```
=> Fix package lookup. Add ast.SelectorExpr

docs/generate/spec/meta.md, fixtures/goparsing/classification/doc.go, scan/meta.go, scan/meta_test.go, scan/path.go, scan/responses.go, scan/routes.go, scan/validators.go
this is fix for issue: #949 
- Security in swagger:meta - nothing has been changed there except I added this to meta
- SecurityDefinitions in swagger:meta new parser for securityDefinitions accepts following, documentation update required
```
SecureDefinitions:
- api_key:
type: apiKey
name: KEY
in: header
```
Now generates the following:
```
"securityDefinitions": {
"api_key": {
"type": "apiKey",
"name": "UHUB_KEY",
"in": "header"
}
},
```
=> Add  in swagger:meta, security fix. Implementation of secure definitions

generator/model.go
There are cases where HasValidations condition is not met,
one of such cases is when a derived model doesn't have any new
attributes.
=> Always add default imports

docs/README.md
=> Fix links in docs/README.md

cmd/swagger/commands/generate/spec.go, scan/scanner.go
When 2 files in the package have different build tags it cause an error that func/struct/whatever not found
```go 
// +build tag1
package something
```
```go 
// +build tag2
package something
```
usage: 
```
swagger generate spec -t 'tag1'
```
=> Allow to set build tags for scanner

docs/generate/spec/meta.md
Allows people to find the actually supported formats.
Updated after: https://github.com/go-swagger/go-swagger.github.io/pull/8#issuecomment-298176500
=> Add the list of supported consumers and producers

cmd/swagger/commands/mixin.go, cmd/swagger/swagger.go, vendor/github.com/go-openapi/analysis/mixin.go, vendor/manifest
Also bumped vendored version of go-openapi/analysis with 'gvt update' for access to the new Mixin func.
=> Add mixin feature that can merge swagger specs. Issue #1005

cmd/swagger/commands/generate/client.go, cmd/swagger/commands/generate/model.go, cmd/swagger/commands/generate/server.go, cmd/swagger/commands/generate/shared.go, generator/client.go, generator/operation.go, generator/shared.go, generator/support.go
Both a client and server can be generated and reference pre-generated
models using the new "existing-models" command-line switch e.g.:
swagger generate server --existing-models="github.com/<repo>/models"
swagger generate client --existing-models="github.com/<repo>/models"
This is a pr that replaces #1033 removing conflicts.
=> Adding ability to use pre-generated models.

generator/operation.go, generator/structs.go, generator/support.go
This includes the `SecurityDefinitions` and `secutiry` configuration in the generator such that these values can be exposed in the templates in order to automatically generate authentication for different routes.
Example of how I use it: https://github.com/mikkeloscar/gin-swagger/blob/master/templates/api.gotmpl#L104-L114
=> Expose operation security and securitydefinitions in templates

fixtures/goparsing/classification/models/nomodel.go, fixtures/goparsing/classification/operations/noparams.go, fixtures/goparsing/classification/operations/responses.go, scan/parameters.go, scan/parameters_test.go, scan/responses.go, scan/responses_test.go, scan/schema.go, scan/schema_test.go, scan/validators.go
Validator is not allow to have field type `integer` and content of `default` other than `integer`
Example which will fail validation:
```go
type  Resp struct {
// default: bar
Field int
}
```
should be:
```go
type  Resp struct {
// default: 0
Field int
}
```
=> Set field default depend on the type of property

generator/template_repo.go
`templatePath` may start with `./`, but the `path` argument of `filepath.WalkFunc` does not start with `./`.
=> Use filepath.Rel to determine template name

docs/usage/validate.md
Update the external link to the semantic validations because the current
one doesn't exist anymore
=> docs: Fix external link to semantic validations

generator/templates/server/configureapi.gotmpl
Like : https://github.com/go-swagger/go-swagger/blob/2e3a56a299279b7041791d1a445518f1420431ad/examples/authentication/README.md
=> Fix typo in configureAPI logger example

README.md, generator/typeresolver_test.go, generator/types.go
mgo compatibility was added to strfmt in https://github.com/go-openapi/strfmt/pull/12
This adds the`strfmt.ObjectId` type to the type resolver.
Signed-off-by: Matt Tucker <matt.tucker@microsoft.com>
Fixes #884
=> add support for strfmt.ObjectId

cmd/swagger/commands/generate/client.go
Can now generate clients using existing-models that have been generated
in another package.
=> Copying missing "existing-models" option

.gitignore, cmd/swagger/commands/generate/client.go, cmd/swagger/commands/generate/model.go, cmd/swagger/commands/generate/operation.go, cmd/swagger/commands/generate/server.go, cmd/swagger/commands/generate/support.go, generator/support.go, generator/support_test.go
Corrected Path generation for Base Imports.
baseImport function now  
- make paths symlink free  
- checks all GOPATH  
- corrected bug in linux environment run of function.
fixes #1059
=> Issue # 1059 : import's are incorrectly generated if $GOPATH is on a symlink. 

cmd/swagger/commands/generate/model.go, cmd/swagger/commands/generate/model_test.go
Models with `x-go-type` cause a panic when generating corresponding files
This patch corrects that
```
sh-3.2$ git rev-parse HEAD ; go run cmd/swagger/swagger.go generate model -f fixtures/codegen/existing-model.yml
3962c9253776ac7c1332321fb391292e13149658
2017/09/07 18:24:41 rendering 1 templates for model JsonWebKeySet
2017/09/07 18:24:41 name field JsonWebKeySet
2017/09/07 18:24:41 package field models
2017/09/07 18:24:41 creating "json_web_key_set.go" in "models" as definition
2017/09/07 18:24:41 generated model JsonWebKeySet
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x156da30]
goroutine 1 [running]:
github.com/go-swagger/go-swagger/generator.(*GenOpts).renderDefinition(0xc4201f03c0, 0x0, 0x0, …
```
=> Generate models that have x-go-type

Gopkg.lock, fixtures/bugs/890/path/health_check.yaml, fixtures/bugs/890/swagger.yaml, generator/client.go, generator/operation.go, generator/operation_test.go, generator/response_test.go, generator/shared.go, generator/support.go, generator/types.go, vendor/github.com/go-openapi/validate/spec.go
Adds support for expansion in abscence of validation.
Updates Vendor dependency package 'validate' which returns
expanded spec.
Minor refactoring for code reusability.
#890
=> Expands spec before generation correctly

cmd/swagger/commands/generate/client.go, cmd/swagger/commands/generate/operation.go, cmd/swagger/commands/generate/server.go, generator/operation_test.go, generator/shared.go
Adds `--skip-flatten` flag to `swagger   ##generate` command for skipping the flattening of spec before generation
#1172
=> Add skip-flatten flag to generate server, client and operation

cmd/swagger/commands/expand.go, cmd/swagger/commands/flatten.go, cmd/swagger/commands/generate/spec.go, cmd/swagger/completion/swagger.zsh-completion
Noticed a typo in the command usages
=> Fix double the typo

fixtures/goparsing/classification/doc.go, scan/meta.go, scan/meta_test.go, scan/scanner.go
Hello,
This is a PR allowing the addition of Vendor Extensions to the info object.
This is useful for ReDoc, to add a logo on the documentation pages, as an example.
Feel free to tell me if anything should be changed !
=> Support adding Vendor Extensions to Infos

docs/tutorial/todo-list.md
* Correct a few typos and formatting.
* Removing https from schema since otherwise examples do not work.
* Updated the -A parameter to reflect the output (todolist vs todo-list)
=> Update verbiage on todo-list tutorial

Gopkg.lock
To pull in this fix for a regression introduced by the last bump
See https://github.com/go-openapi/spec/pull/40
=> Bump go-openapi/spec

generator/template_repo.go, generator/template_repo_test.go
- Tested more error cases.
- Enriched error messages from template repo.
- Suppressed 1 log.Fatal() by return err for better testability.
Overall, test coverage of template_repo.go should reach about 92%.
=> Enriched UT on template_repo.go

generator/build_test.go, generator/model_test.go, generator/operation_test.go, generator/parameter_test.go, generator/response_test.go, scan/scanner_test.go
Minor change in order to better get the essentials when running CI checks.
=> 1299-fix-unit-test-verbosity

cmd/swagger/commands/validate_test.go, fixtures/bugs/1171/swagger.yaml
Issue#1171 has been much embroiled...
There are basically 2 cases mentionned:
- object with an items property : covered with fixture for issue#1238 (more or less a duplicate of #1171, only clearer)
- items missing in array. This case specifically covered by the present fixture.
Together with issue#1238, both cases discussed are covered by UT (new exerciser for cmd/swagger/validate).
=> 1171. Add fixture

generator/client.go, generator/client_test.go, generator/config.go, generator/model.go, generator/operation.go, generator/shared.go, generator/support.go, generator/support_test.go
Hi,
I moved the go specific baseImport code into the new function attached to LanguageOpts so that this code can be customized.
@casualjim Please let me know if this fits to what you are thinking about.
Thanks,
aki
fixes #1312
=> move language specific baseImport check to LanguageOpts #1312

docs/tutorial/todo-list.md
Mostly this consisted of going through the tutorial and editing for English
grammar as well as trying to trim down the word count. The text was a bit more
verbose than it needed to be, which I think made it harder to follow.
I also made a few other changes:
* Wrapped more things in backticks to highlight technical terms, code
snippets, etc.
* Updated output examples to match the current state of go-swagger (notably
the generate files have changed a bit).
=> Edit the todo tutorial for grammar and clarity

generator/shared.go, generator/support.go
Generated codes on Windows by go-swagger can't be compiled when the package path has case sensitive name.
For example, the name of pacakge is `github.com/FooBar/awesome`, go-swagger generate codes which have `"github.com/foobar/awesome/xxx"` or so in import paths on Windows.  It causes compilation errors because golang compiler checks import paths by case sensitive.
This PR modifies `checkPrefixAndFetchRelativePath()` function to compare two paths by case insensitive on Windows, but create relative path by case sensitive.
=> case sensitive import path on Windows

appveyor.yml, fixtures/bugs/1348/fixture-1348.yaml, generator/debug.go, generator/doc.go, generator/formats.go, generator/model_test.go, generator/shared.go, generator/types.go
This PR provides the generation part for #1348
The fix will be effective with the validation part, starting with go-openapi/validate#50
Plus:
Minor refactoring:
split format definitions, reorder them and check they match definitions strfmt default registry (e.g. for bsonobjectid)
split debug related definitions
some layout, structuring in doc.go
=> 1348 Add generation of validate on MAC format

generator/structs.go, generator/support.go
The array used to generate the models is not currently sorted, so
the models are generated in whatever order comes out of the map.
When there are multiple models that fail to generate properly, this lack
of sorting results in changes in the reported failures from run to run.
Sorting results in deterministic behavior in the case of errors, making
it easier to fix the errors.
The generated operations are being sorted, this just applies the same
pattern to the models as well.
Signed-off-by: Greg Marr <greg.marr@autodesk.com>
=> Make generate server sort the models #1349

generator/operation.go, generator/structs.go
**What This PR Includes**
go-swagger's `GenOperation` struct only supports checking for the presence of query parameters (via the `HasQueryParameters` field). This pull request adds similar fields for path, header, and body parameters.
=> Support checking presence of path, header, and body parameters

docs/generate/server.md
The newly generated server code uses `github.com/go-openapi/runtime` for consumer and producer.
=> docs: replace `httpkit` with `runtime`

README.md, docs/README.md
This adds @casualjim's suggestion from https://github.com/go-swagger/go-swagger/issues/754#issuecomment-262822894 to the docs.
=> Document how to avoid "target must reside inside a location in the $GOPATH/src" using docker

generator/discriminators.go, generator/model.go, generator/operation.go, generator/typeresolver_test.go, generator/types.go
Small refactoring on custom extensions usage:
- declare supported extensions as constants in types.go
- propagate extensions in resolverType
=> Small refactoring on custom extensions usage

docs/use/middleware.md
Fix a few spelling and grammar errors in the middleware doc.
=> Fix typos in docs/use/middleware.html

fixtures/goparsing/classification/models/nomodel.go, scan/schema.go, scan/schema_test.go
Sometimes it's useful to includ a field in a request or response but leave it
undocumented. This change allows such struct fields to be annotated with
`swagger:ignore`, e.g.
```go
type Foo struct {
// swagger:ignore
Bar string `json:"bar"`
}
```
See #1497.
Signed-off-by: Neil Garb <neil@luno.com>
=> Allow struct fields to be annotated with swagger:ignore

fixtures/enhancements/1557/swagger.yml, generator/server_test.go, generator/support.go
Fixes #1284 
Specifying consumers/producers that are not explicitly added to the whitelist will create an empty handler. Here are some example generated handlers for content types `application/pdf` and `text/csv`:
```go
api.ApplicationPdfConsumer = runtime.ConsumerFunc(func(r io.Reader, target interface{}) error {
return errors.NotImplemented("applicationPdf consumer has not yet been implemented")
})
api.ApplicationPdfProducer = runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
return errors.NotImplemented("applicationPdf producer has not yet been implemented")
})
api.CsvProducer = runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
return errors.NotImplemented("csv producer has not yet been implemented")
})
```
Since the …
=> Generate consumer/producer handlers that are not whitelisted

docs/install.md
Add missing slash in git clone command.
=> Fix typo in clone command

README.md
Added Nutanix to the list of companies using go-swagger. 
We're using this for swagger validate internally to ratchet up the quality gate for our various internal swagger.json/swagger.yaml implementations, as well as using swagger generate for nusights, which is one of our telemetry frameworks.
=> Update README.md to add Nutanix to the list

README.md, docs/README.md, docs/use/models/schemas.md
* references to v1.0 moved to v0.15
* table alignment in schemas.md
* some typos in new doc material
=> Fixes minor glitches in documentation

generator/operation.go
`generate xxx` (`planning operations` phase) is too slow.
`codeGenOpBuilder.MakeOperation()` takes about 500msec for **an operation** in my env.
And I have over 100 operations in my swagger.yml, then...
500msec/op * 100op = 50s
It takes about 1min.
---
This is caused by `codeGenOpBuilder.saveResolveContext` (actually `cloneSchema()` is too slow).
So I optimize to call it when those backups are never used.
=> optimize to clone schema

generator/model.go, generator/shared_test.go
Adding support for the x-order custom tag silently (and slightly) changed behavior with x-go-custom-tag.
Reverted to the original behavior.
=> Reverts silent change brought by #1612

generator/formats.go, generator/typeresolver_test.go, generator/types.go
The before implementation checks format only but it causes wrong type decisions.
e.g. {"type": "string", "format": "uint64"} had been converted to uint64.
This behaivior is correct in case of "type" is "integer" or "number", but the "string" case is not.
This commit changes this decision algorithm. "format" is not treated as same of "type" anymore.
"format" must be available when it is specified with the valid (matched) "type". If not, the "format" will be ignored
and it just decides the type of Go code by using "type" value.
=> Make format resolving strictly to require a valid pair of type and format.

generator/moreschemavalidation_test.go, generator/shared.go
This improves the `go.mod` support added in #1636 by adding support for
targets not at the module level.
Imagine you generate code like this:
```bash
$ swagger generate client --name my-api --target ./pkg/api
```
Then it would assume `go.mod` is under `pkg/api` and not detect that go
modules are used. The fix is to walk up the directory to find the first
occurance of `go.mod` and assume that as the module base URL.
=> Improve go.mod support in generator

generator/moreschemavalidation_test.go
Parallel testing on model generation is a headache (essentially because
of cached ref resolution in go-openapi/spec).
After several unsuccessful attempts to gain a few seconds of CI time,
I eventually roll back to serialized model testing... :-(
=> Gave up with parallel testing

cmd/swagger/commands/generate/client.go
user is not required to install old version of context
=> remove telling user they need to install context package

cmd/swagger/commands/generate/spec.go, cmd/swagger/commands/generate/spec_test.go, fixtures/goparsing/spec/api.go, fixtures/goparsing/spec/api_spec.json, fixtures/goparsing/spec/api_spec.yml
When user run the generate command with a output file which has .yml or .yaml suffix. The swagger will generate yaml format output
=> Add yaml format spec support

scan/parameters.go, scan/schema.go, scan/schema_test.go
Right now, when generating swagger spec, Go language extension is added by default. Make Go language extension generation optional by setting up an env variable. By default, it is still generating Go extension spec unless the env variable `SWAGGER_GENERATE_EXTENSION` set to `false`
The use case is when visualization of the spec or generate code in other language by using the spec file (generated by go-swagger), we don't wanna these language specific extension appeared in the spec file as it may not make sense to other language.
Usage:
```
export SWAGGER_GENERATE_EXTENSION=false
swagger generate spec -o openapi.yml -q
```
=> Make extension generation optional

cmd/swagger/commands/generate/spec.go, scan/classifier.go, scan/scanner.go, scan/scanner_test.go
Add include/exclude parameters to spec generator. Both are treated as a regular expression against package name and allow to narrow the list of analyzed packages.
=> Add include/exclude parameters to spec generator

generator/shared.go
This is a follow up to #1661 which correctly handles relative paths when using go modules.
#1661 didn't account for situations where you want to generate server code in a sub package of your module, so it generated the wrong imports because it used the go module path as base import instead of go module + relative package.
E.g. if you had a module `github.com/a/b` and wanted to generate go-swagger code from the package `github.com/a/b/my-server` then the import paths would be `github.com/a/b/restapi/..` instead of `github.com/a/b/my-server/restapi/..`.
=> Handle relative path when using Go modules

scan/route_params.go
When run 
swagger generate spec -o swagger.json 
i got follow issue
```
Rinats-MacBook-Pro:gomoona rinat$
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x118 pc=0x1603e4a]
goroutine 1 [running]:
github.com/go-swagger/go-swagger/scan.(*setOpParams).Parse(0xc42e2476e0, 0xc423b9fb00, 0x5, 0x8, 0xc423b9fb00, 0x0)
/Users/rinat/dev/go/src/github.com/go-swagger/go-swagger/scan/route_params.go:109 +0x29a
github.com/go-swagger/go-swagger/scan.(*tagParser).Parse(0xc4205cf310, 0xc423b9fb00, 0x5, 0x8, 0x0, 0xc423b9fb00)
/Users/rinat/dev/go/src/github.com/go-swagger/go-swagger/scan/scanner.go:558 +0x52
github.com/go-swagger/go-swagger/scan.(*sectionedParser).Parse(0xc4205cf9f0, 0xc42e247340, 0xc4205cf620, 0xd) …
```
=> There is a panic when invalid schema of route/operation is used in spec generation. It should prevent it

fixtures/goparsing/spec/api.go, fixtures/goparsing/spec/api_spec.json, fixtures/goparsing/spec/api_spec.yml, scan/validators.go
The OpenAPI 2.0 spec allows examples to be any JSON value. Currently,
go-swagger supports most types (e.g. ints and strings), but not objects.
This adds support to parse object examples as JSON, allowing users to
document examples for maps.
=> Use JSON for examples of type object

Gopkg.lock, vendor/github.com/go-openapi/loads/.golangci.yml, vendor/github.com/go-openapi/loads/README.md, vendor/github.com/go-openapi/loads/doc.go, vendor/github.com/go-openapi/loads/fmts/yaml_test.go, vendor/github.com/go-openapi/loads/json_test.go, vendor/github.com/go-openapi/loads/spec.go, vendor/github.com/go-openapi/loads/spec_test.go, vendor/github.com/go-openapi/swag/.golangci.yml, vendor/github.com/go-openapi/swag/util.go, vendor/github.com/go-openapi/swag/util_test.go, vendor/github.com/go-openapi/swag/yaml.go, vendor/github.com/go-openapi/swag/yaml_test.go
improve `swagger generate server` performance on a large schema.
related pull requests:
* https://github.com/go-openapi/swag/pull/25
* https://github.com/go-openapi/loads/pull/19
before:
after:
=> chore: update vendor for performance

Gopkg.lock, Gopkg.toml, fixtures/bugs/1816/fixture-1816.yaml, generator/server_test.go, vendor/github.com/go-openapi/loads/fixtures/bugs/1816/fixture-1816.yaml, vendor/github.com/go-openapi/loads/spec.go, vendor/github.com/go-openapi/loads/spec_test.go, vendor/github.com/go-openapi/spec/ref.go, vendor/github.com/go-openapi/spec/ref_test.go
* update vendor:  go-openapi/spec, go-openapi/loads
* fixes #1816 
~~> NOTE: this is WIP and would require go-openapi/spec#87 and go-openapi/loads#22 to be merged.~~ 
=> Acknowledge fix #1816 with go-openapi updates

docs/use/spec/model.md, docs/use/spec/params.md, docs/use/spec/response.md, fixtures/goparsing/spec/api.go, fixtures/goparsing/spec/api_spec.json, fixtures/goparsing/spec/api_spec.yml, scan/validators.go
I previously added JSON parsing for examples on object types; this adds
it for array types. It also adds basic documentation for Example.
=> Handle array examples; document Example usage

fixtures/goparsing/classification/operations/todo_operation.go, scan/routes_test.go, scan/validators.go
https://github.com/go-swagger/go-swagger/issues/1828
=> route: add support description response tag at path

cmd/swagger/commands/expand.go, cmd/swagger/commands/flatten.go
It took me some time to figure out why `flatten` does not work for me.
=> Check that only a single parameter is passed.

cmd/swagger/commands/expand_test.go
Hi! I've just added one test case for cover the brand where output file is not defined on `expand.go`. Please review this
=> Add test case without output file for expand.go

scan/responses.go
https://swagger.io/docs/specification/2-0/describing-responses/ section: `Response That Returns a File`
An API operation can return a file, such as an image or PDF. In this case, define the response schema with type: file and specify the appropriate MIME types in the produces section.
Example:
```
--- Go source:
// swagger:response routeRequest
type response struct {
// swagger:file
// in:  body
File []byte
}
--- Result:
"responses": {
"routeRequest": {
"schema": {
"type": "file"
}
}
},
```
=> spec gen/response: support swagger:file

fixtures/codegen/x-order.yml, generator/model_test.go, generator/structs.go
Currently if only some properties define x-order, they will potentially be generated between the others that don't because the current sorting comparator takes x-order into account only if both compared properties have it.
=> Generate properties with x-order above ones without

generator/types.go
Currently there is no way to set x-go-type to another generated type.
=> x-go-type: if no imports are specified, assume that the referred type is inside the same package

cmd/swagger/commands/generate/server.go, fixtures/codegen/keep-spec-order.yml, generator/model_test.go, generator/shared.go, generator/support.go
This PR solves issue #125 (Keep object's parameters order as specified in swagger spec definition).
Before loading the spec , if argument--keep-spec-order exists , it will inject x-order attribute to each property which is equal to its position in the spec file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/go-swagger/go-swagger/1939)
=> support keep spec properties order

fixtures/goparsing/classification/operations/noparams.go, scan/parameters.go, scan/parameters_test.go, scan/responses.go, scan/schema.go, scan/validators.go
add correct enum parsing according variable type. 
**This not take care about named enums, only fix correct exposing integer enums into spec.**
Example:
`enum: 1,2,3`
result for int variable :
`          "type": "integer",
"format": "int64",
"default": 1,
"enum": [
1,
2,
3
],`
fix https://github.com/go-swagger/go-swagger/issues/1672
actually this not fix only integer as uses type parse of provided values.
=> scan: proper parse for numeric elements (future validation pass)

generator/operation.go, generator/operation_test.go, generator/shared.go, generator/support.go
as for only-one-tag operations, instead of default "operations" as when no
tags are available.
Should solve #1950 (tested for server generation only)
* fixes #1950
=> Multiple tags operations: deduce package from first tag

.codecov.yml
exclude bindata.go from test coverage computation
=> chore(ci): set codecov patch expectation to a fixed level

fixtures/bugs/1893/.gitignore, fixtures/bugs/1893/fixture-1893.yaml, fixtures/bugs/1893/gen-fixtures.sh, generator/operation.go, generator/response_test.go, hack/codegen-nonreg.sh
* fixes #1893
* codegen (client and server) now supports codes other than the well-known ones published by go-openapi/runtime
=> Added support for non-standard http codes

fixtures/goparsing/classification/models/nomodel.go, scan/schema.go, scan/schema_test.go
This is an update of pull request: #1511
For example:
```
// swagger:model Foo
type Foo struct {
Bar *int64 `json:"bar,omitempty,string"`
}
```
The generated spec should be type "string" and format "int64".
=> Honour JSON ,string directive of ptr field when generating spec

.circleci/config.yml, hack/deploy.sh
Fixes #1873 (for next release)
@casualjim do you have the possibility to manually tag v0.0.19 as latest on quay.io?
=> fixed push latest tag on releases

.golangci.yml, fixtures/bugs/1042/pet_test.go, fixtures/bugs/1232/discriminatedMarshalling_test.go, fixtures/bugs/1548/base64Thing_test.go, fixtures/bugs/1571/tupleThing_test.go, fixtures/bugs/1851/.gitignore, fixtures/bugs/1851/definitions.yaml, fixtures/bugs/1851/fixture-1851.yaml, fixtures/bugs/1851/gen-fixtures.sh, generator/shared_test.go, go.mod, go.sum, hack/codegen-nonreg.sh
updates from latest tag on go-openapi/analysis
* fixes #1851
* fixes #1965
* fixes #1886
* reactivated test on windows for #1429
* Fixed build tag issues in some fixture go source (prevented go mod vendor)
* Update vendor (go mod vendor)
* Added fixture to assert #1851 is fixed
Update go-openapi/analysis dependency
=> Integrates flatten fixes

fixtures/bugs/1937/.gitignore, fixtures/bugs/1937/fixture-1937.yaml, fixtures/bugs/1937/gen-fixtures.sh, generator/parameter_test.go, generator/shared.go, hack/codegen-nonreg.sh
updated from latest tag of go-openapi/swag
Handling of names not starting with a letter (mismatches between GoType and model name)
This makes the pascalize and swag.ToGoName funcs work with similar rules.
* fixes #1937
=> Codegen edges cases

hack/codegen-nonreg.sh
=> ci: made codegen-nonreg.sh script less sensitive to merge conflicts

.circleci/config.yml, codescan/application.go, codescan/application_test.go, codescan/parameters.go, codescan/parameters_test.go, codescan/responses.go, codescan/responses_test.go, codescan/schema.go, codescan/schema_test.go, codescan/spec.go, docs/install.md, fixtures/goparsing/petstore/rest/app.go, fixtures/goparsing/petstore/rest/handlers/orders.go, go.mod, go.sum
Use slices to store the decls for responses and parameters. 
fixes #1997 
fixes #2001
=> use slices for collecting parameters to retain ordering

codescan/application_test.go, codescan/parser.go, codescan/regexprs.go, codescan/routes.go, fixtures/goparsing/petstore/rest/handlers/pets.go
=> spec generation: added support for deprecated tag in route annotations

fixtures/bugs/2050/.gitignore, fixtures/bugs/2050/fixture-2050.yaml, fixtures/bugs/2050/gen-fixtures.sh, generator/shared.go, generator/shared_test.go, generator/template_repo_test.go, hack/codegen-nonreg.sh
* fixes #2050
* added support for "#" prefix handling values like '#235'
* more unit testing on the pascalize function
=> Fixed regression on name generation for "+" or "-" enum values

examples/tutorials/todo-list/server-complete/restapi/configure_todo_list.go
this PR brings back command-line flag example from PR https://github.com/go-swagger/go-swagger/pull/573  which was later removed by https://github.com/go-swagger/go-swagger/commit/9e978bcf2fff35aff57c7af1360d8f8f3d045d59#diff-6da81f07c9f2d75a4f98a7f45a6f36a0
@casualjim can you take a look, I don't believe it was intended to remove flags example...  
Also adding "usage" of the flags for clarity...
=> Provide example for configure command-line flags

Dockerfile
This will allow using the --template-dir parameter when using the
go-swagger container
=> added contrib to the docker image

cmd/swagger/commands/serve.go
fix #2078
The goal is to be able to serve a swagger spec containing external
$ref.
* Added a `Flatten` flag to `ServeCmd`
* Flatten spec if flag is present
=> Feat(serve) : Add flatten flag to serve command

cmd/swagger/commands/generate/server.go, cmd/swagger/commands/generate/shared.go, docs/generate/client.md, docs/generate/model.md, docs/generate/server.md, generator/client.go, generator/model.go, generator/operation.go, generator/shared.go, generator/support.go, generator/template_repo.go, generator/template_repo_test.go
Gives option to the user willing to take the risk to overwrite templates
protected by go-swagger by passing --allow-template-override flag.
Related to #1606
=> Add flag to allow overwriting protected templates

codescan/schema.go
Before this patch, `encoding/json.RawMessage` would be interpreted as []uint8, which `encoding/json` is incapable of decoding. This patch addresses that by checking if a type's name is `encoding/json.RawMessage` and if so, sets `type: object`.
In #1622 it was suggested to use `type: string` with `format: binary` which is however not the correct use, because this is not an serialized JSON object but a deserialized JSON object.
If my understanding is correct, `type: string` with `fromat: binary` would expect something like:
```
{ "foo": "[\"bar\"]" }
```
for
```
type f struct { Foo json.RawMessage `json:"foo"` }
```
whereas `json.RawMessage` actually implies:
```
{ "foo": ["bar"] }
```
I've tried to mess around with `x-go-type`
```go
tgt.AddExtension("x-go-type", map[string]interface{}{ …
```
=> codescan: Natively support json.RawMessage

generator/operation.go
b.Doc.Pristine() is surprisingly slow, so keep it once it is produced.
This change speeds up `swagger generate` on one YAML file from 7.9s to 3.9s.
=> Speedup 'swagger generate' by not re-parsing schemas many times

generator/operation.go, generator/operation_test.go
* param "time-out" is detected as a conflict
* adopts a more agressive, deterministic, deconflicting when all baked proposals are already taken
* added unit test, which was missing on this func
=> fixed some edge cases when deconflicting client timeout parameters

Dockerfile.alpine.ci, Dockerfile.ci
* replaced deprecated gem install options, which are no more supported by gem
Trying to address this CI failure:
https://app.circleci.com/jobs/github/go-swagger/go-swagger/4135
=> Fixed release Dockerfiles

.circleci/config.yml, hack/codegen_nonreg_test.go
Codegen test in CI is running parallel code generation jobs. This
may be memory consuming, and whenever several large specs are
picked in parallel, may fail on memory limits (4 GB on circleCI VM).
This fix throttles the number of concurrent codegen jobs, trading
speed for memory.
=> Throttle memory in codegen CI

fixtures/bugs/2116/.gitignore, fixtures/bugs/2116/fixture-2116.yaml, fixtures/bugs/2116/gen-fixtures.sh, fixtures/enhancements/1623/swagger.yml, generator/model_test.go, generator/moreschemavalidation_fixtures_test.go, generator/moreschemavalidation_test.go, generator/types.go
**ATTENTION: there is a subtle change in here that SHOULD be discussed before blindly merging!!!**
* fixes #2116
* tests are embedded with existing testcase for #1623 (added by #1751)
* ensure arrays _of primitives_ are not omitempty-ed by default, including arrays declared as properties
* arrays as aliased types used as properties remain empty-omitted by default (this may be altered with the x-omitempty extension)
@zhuangqh this brings some slight changes to your PR #1751. Visible outcome is:
- extensions declared as siblings to $ref are ignored
- properties which _are_ arrays are not always empty-omitted by default: to avoid introducing breaking changes I adopted the rule array of primitive vs aliased array
@zhuangqh since you brought in that change in the first place, I'd like to have …
=> Fixed x-omitempty in the case of $ref'ed schemas

cmd/swagger/commands/generate/client.go, cmd/swagger/commands/generate/client_test.go, cmd/swagger/commands/generate/contrib.go, cmd/swagger/commands/generate/model.go, cmd/swagger/commands/generate/model_test.go, cmd/swagger/commands/generate/operation.go, cmd/swagger/commands/generate/operation_test.go, cmd/swagger/commands/generate/server.go, cmd/swagger/commands/generate/server_internal_test.go, cmd/swagger/commands/generate/server_test.go, cmd/swagger/commands/generate/shared.go, cmd/swagger/commands/generate/shared_test.go, cmd/swagger/commands/generate/support.go, cmd/swagger/commands/generate/support_test.go, docs/generate/client.md, docs/generate/model.md, docs/generate/server.md, generator/build_test.go, generator/shared.go
* introduced flags groups in CLI for more readable usage text
* refactored CLI to simplify the process of transforming input flags into GenOpts
Sample help from CLI:
```
Usage:
swagger [OPTIONS] generate model [model-OPTIONS]
generate one or more models from the swagger spec
Application Options:
-q, --quiet                                                                     silence logs
--log-output=LOG-FILE                                                       redirect logs to file
Help Options:
-h, --help                                                                      Show this help message
[model command options]
--skip-struct                                                           when present will not generate the model struct
-n, --name= …
```
=> CLI: refactored CLI commands to introduce command groups

codescan/application.go
When `codescan/application.go` was created, the continues in
(*typeIndex).processDecl() were commented out. This led to issues if
there were structs declared in the package that were unrelated to the
swagger api (no swagger declaration type).
Signed-off-by: Pat Long <pllong@arista.com>
=> Fix processing type declarations

generator/build_test.go, generator/client.go, generator/client_test.go, generator/debug.go, generator/discriminators_test.go, generator/generate_test.go, generator/language.go, generator/language_test.go, generator/model.go, generator/model_test.go, generator/moreschemavalidation_test.go, generator/operation.go, generator/operation_test.go, generator/parameter_test.go, generator/response_test.go, generator/schemavalidation_test.go, generator/server_test.go, generator/shared.go, generator/shared_test.go, generator/spec.go, generator/spec_test.go, generator/support.go, generator/support_test.go, generator/template_repo.go, generator/template_repo_test.go, generator/types.go
NO BEHAVIOR CHANGE EXPECTED
* removed some (most) redundant code (left redundancies that would introduce change in behavior to forthcoming PRs)
* factorized spec loading/validating/flattening operations (new spec.go file)
* regrouped state init() function calls
* reduced the number of global vars and replaced them by functions
* adapted template repo to initialize from language options, with adequate template FuncMap
* made DefaultLanguage a configurable function
* moved global golang-specific function to LangueOpts (new language.go file)
* testability: functionalized a number of hard to test code (e.g. all funcmap entries), and introduced unit testing
* started, but did not complete yet the rewriting of unit tests using 'require' instead of nested constructs with 'assert'
Signed-off-by: …
=> refactored code generator

cmd/swagger/commands/generate/model.go, generator/shared.go, generator/support.go
Attempt at solving #1679
I have manually tested this will output all the expected go code for definitions defined in a swagger spec where `paths: {}`.
This is my first contribution, so apologies if I've missed anything. I'm guessing I might need to add some tests, any pointers into that would be appreciated.
Signed-off-by: dan-j <5727701+dan-j@users.noreply.github.com>
=> add option in model generation to output all definitions regardless of usage

README.md, docs/README.md
* fixes  #2206
This changes the name of project for go-netbox in docs
=> Fix #2206: Change project name for go-netbox

codescan/application.go, codescan/spec.go
@fredbi @casualjim instead of copying the map  before iteration I removed the place where `Models` is being modified, I think that was wrong, at this stage model should be known and embedded should not be added as a "standalone" model. Does that make sens to you? I updated related tests too.
Please take a look, thanks.
EDIT: I changed approach, to be sure that all models are processed (with extra ones), I added a new map `ExtraModels` which is joined later to `Models`. `Models` cannot be updated during iteration.
=> fix go-swagger#2066 issue

docs/install.md
documentation update:
run swagger on current user uid:guid instead of root
-> no more file owned by root :-)
=> [DOCKER] don't run swagger with "root"

cmd/swagger/commands/generate/model.go
Bugfix for #2281.
I'm not sure what happened but this line got lost when I created the previous PR, so the struct tags were never passed from the command line options to the generator.
=> Set struct tags on generator options

docs/generate/client.md, docs/generate/server.md
For starters, at least some documentation, see #2256.
I decided to primarily put it into the client.md, because I had an example ready. And who would voluntarily _provide_ an XML API anyways ;)
Maybe the generate client documentation needs an update in general, also see #2243. For me it was trial and error as well, maybe someone can shed some light on that.
=> Improvements for XML support

codescan/schema.go, go.mod
fix nil pointer panic
go version: 1.13
=> fix: afld check nil

fixtures/bugs/2278/fixture-2278.yaml, generator/bindata.go, generator/build_test.go, generator/client_test.go, generator/shared.go, generator/shared_test.go
* fixes #2293
* fixes #2278
Having API name terminated by "api" is no more causing name conflicts in generated code.
However, generated names may stutter like "xxxAPIAPI". This is not blocking.
=> fix(generator): fixed generated API name when terminated with suffix "api"

generator/bindata.go, generator/client.go, generator/operation.go, generator/shared.go, generator/shared_test.go, generator/support.go
* fixes #2283
NOTE:
* default principal is "interface{}"
* principal specified with simple package (e.g. auth.Principal) is assumed to be imported from target generation (base import)
* principal specified with fully qualified name (e.g. github.com/myproject/auth.Principal) is imported from that location
Also in this commit:
* fixes package alias for when specifying existing external models
* more tests on default imports
=> fixed broken imports when specifying principal in external package

cmd/swagger/commands/generate/operation.go, generator/bindata.go, generator/operation.go, generator/shared.go, generator/structs.go
* Also fixed similar issue with selected models
* fixes #2280
Also in this commit:
* ordered operations in dump data
=> fix(cli): filter out empty args passed by CLI to select operations

.circleci/config.yml
* fixes #2257
**NOTE**:
golangci hosted service has closed. We have to run it from CI.
I haven't tried github's super-linter yet: just wanted to lint our golang code again and not to
re-lint the entire repo with Dockerfiles, sh scripts etc.
=> re-enacted CI-based linting

docs/use/spec/meta.md
Add NOTE in `swagger:meta` for adhering to godoc standard
=> Add NOTE in swagger:meta for adhering to godoc standard

README.md, cmd/swagger/commands/generate/model.go, docs/generate/model.md, fixtures/enhancements/2333/fixture-definitions.yaml, generator/generate_test.go, generator/model.go, generator/model_test.go, generator/operation.go, generator/shared.go, generator/spec.go, generator/support.go
Feature
* added --accept-definitions-only option to generate model from a spec with only definitions (not the complete swagger spec)
Deprecated CLI options
* deprecated generate model option: --skip-struct (was inoperant)
* deprecated generate model option: --all-definitions (now the default behavior, as previously documented)
* updated usage doc for generate model CLI
* added deprecation notice to README (no breaking change introduced on CLI)
Refactoring
* refactored generate model command to use standalone model codegen func generator.GenerateModels (now in line with other commands)
* refactored places where GenOpts.IncludeValidator is hard-coded to true, in order to drive this parameter from one single place (unused, but might come back)
* refactored test for full server codegen, …
=> Enhanced generate model CLI: accepts definitions only specs, deprecates some options

fixtures/bugs/2161/fixture-2161-panic.json, generator/model.go, generator/operation_test.go
* fixes #2161
> NOTE: this tests against the fixture brought by #2156, which comes with many still unsupported features
> (cascading subtyping, validation-only allOf schemas).
> This commit just makes sure there is no panic. I know that the models generated from the fixture are not correct.
=> fix edge case with panic in models because of invalid additionalProperties or AllOf schema

generator/bindata.go, generator/operation_test.go
Automatic merge caused some goimport/linting errors to appear.
=> fixed merging issues that caused linting/goimport failures

cmd/swagger/commands/generate/operation.go
Two line PR, adds `-m` for setting `ModelPackage` in the operations generator options.
=> Adding ModelPackage option to generate operation

generator/bindata.go, generator/model.go, generator/model_test.go, generator/templates/docstring.gotmpl
In our workflow we are using the `swagger.yaml` as a source to generate the models then we generate the `swagger.json` to use in some other services.
There is a problem, we have some examples in the `swagger.yaml`, but the generated models don't have those examples, and the generated `swagger.json` from the code also don't have those examples.
This PR fixes the problem.
=> Pass examples to the generated models

fixtures/enhancements/1771/.gitignore, fixtures/enhancements/1771/fixture-1771.yaml, fixtures/enhancements/1771/gen-fixtures.sh, fixtures/enhancements/2163/.gitignore, fixtures/enhancements/2163/fixture-2163.yaml, fixtures/enhancements/2163/gen-fixtures.sh, generator/build_test.go, generator/operation.go, generator/shared.go, generator/types.go, hack/codegen-fixtures.yaml
* for schemas and simple schemas (parameters and headers)
* protects codegen against invalid specifications, with validation not supported by the specified type
* the guard is non-blocking: a warning is issued during codegen and the invalid validation is skipped
* enum validation is always allowed
Examples:
- minimum on a string
- maxitems on a number
- ...
* fixes #2163 (schemas)
* fixes #1771 (simple types)
=> added validation guards against inconsistent validations

fixtures/bugs/1487/gen-fixtures.sh, fixtures/bugs/2364/.gitignore, fixtures/bugs/2364/fixture-2364.yaml, fixtures/bugs/2364/gen-fixtures.sh, fixtures/bugs/2381/fixture-2381.yaml, fixtures/bugs/2400/.gitignore, fixtures/bugs/2400/fixture-2400.yaml, fixtures/bugs/2400/gen-fixtures.sh, generator/model.go, generator/moreschemavalidation_fixtures_test.go, generator/moreschemavalidation_test.go, generator/pointer_test.go, generator/typeresolver_test.go, generator/types.go
Whenever a required property is an aliased type, it is rendered with a pointer type (not if interface{}).
* Changed the nullability assessment of aliased types: it now inherits from the nullable decision taken at a lower level (within $ref)
* Fixed ability to override nullability for AllOf, now x-nullable extensions in AllOf are honored
* fixes #2400
=> Fixed required aliased type

fixtures/bugs/1897/.gitignore, generator/.gitignore, generator/build_test.go, generator/client_test.go, generator/discriminators_test.go, generator/enum_test.go, generator/generate_test.go, generator/model_test.go, generator/moreschemavalidation_test.go, generator/operation_test.go, generator/parameter_test.go, generator/schemavalidation_test.go, generator/server_test.go, generator/shared.go, generator/shared_test.go, generator/support.go, generator/support_test.go, generator/template_repo.go, generator/types_test.go, generator/utils_test.go, go.mod, go.sum
* updated go-openapi dependencies to fix race conditions on parallel spec processing
* adapted tests to process fixtures in parallel
* refactored tests for readability (e.g. require... instead of if assert...)
* fixed race condition on global templates when testing in parallel:
* templates are now a shadow clone in GenOpts: now generation can proceed in parallel, even with contrib templates
(custom templates from config remain loaded in the global templates)
=> test: model tests go parallel

docs/use/model.md, docs/use/models/schemas.md, generator/model.go, generator/model_test.go, generator/structs.go, generator/structs_test.go
* fixes #2423 - acknowledged fixed
* refactored tag rendering: use strings.Builder, cleaned up redundancies with xml tags,
used stdlib strconv.CanBackQuote instead of Contains
* now always renders extra tags in order specified by the user (e.g. --struct-tags example,db)
* now renders xml tags if requested in the CLI opts, even when no consumes/produces is set with xml
* added unit tests for model tag generation
* added doc on how to play with struct tags
=> refactored, documented and tested tags in models

cmd/swagger/commands/version.go
CLI version: added versioning from module support for go get users
* go-swagger version is now properly displayed when building from source using go get:
go get -u github.com/go-swagger/go-swagger/cmd/swagger
swagger version
version: v0.25.0
...
* no change for released binary versions
* no change for versions build from source repo (e.g. "dev")
* fixes #1283
* fixes #2454
=> CLI version: added versioning from module support for go get users

docs/install.md
Add information how to install specific version from source and how to set `-ldflags` so swagger version reports that version and commit id instead of just `dev`.
Fixes #2474
=> add specific version install info

generator/template_repo.go, generator/template_repo_test.go
Fixes #2501
I re-ran `swagger generate client` using this version and verified that it fixed the issue. The generator now correctly outputs:
```golang
const (
// ModificationSourceOperationEqualSign captures enum value "="
ModificationSourceOperationEqualSign string = "="
// ModificationSourceOperationPlus captures enum value "+"
ModificationSourceOperationPlus string = "+"
// ModificationSourceOperationDash captures enum value "-"
ModificationSourceOperationDash string = "-"
// ModificationSourceOperationAsterisk captures enum value "*"
ModificationSourceOperationAsterisk string = "*"
// ModificationSourceOperationForwardSlash captures enum value "/"
ModificationSourceOperationForwardSlash string = "/"
)
```
=> Generator: Handle special characters *, /, and =

docs/tutorial/authentication/README.md, examples/authentication/README.md
Authentication tutorial does not provide details about the changes required to the Swagger spec to allow proper generation of Principal and security-related code.
Fixes: #2530
=> Update Authentication tutorial with spec changes

docs/install.md
I fixed a typo in docs/install.md. Please check my change.
source:
https://github.com/go-swagger/go-swagger/blob/3af79747ddab32ed5bd694514599f06e4299bca4/docs/install.md
Fixes https://github.com/go-swagger/go-swagger/issues/2550
Signed-off-by: masa08 <ushimasarug08@gmail.com>
=> Fix a typo in install.md

docs/use/models/schemas.md, generator/structs.go, generator/structs_test.go
Addresses https://github.com/go-swagger/go-swagger/issues/2541 : introduces support for `--struct-tag description` to the code generator.
Signed-off-by: Arne Redlich <arne.redlich@gig.tech>
=> generator: introduce support for "description" struct tag

generator/templates/schemavalidator.gotmpl, generator/templates/server/parameter.gotmpl
Update templates that have nested body param logic to call ValidateName API on CompositeError.
See https://github.com/go-openapi/errors/pull/30 for addition of ValidateName API to CompositeError which needs to be committed prior to this.
Closes #2594
=> Support nested body params for CompositeError

codescan/route_params.go, codescan/routes_test.go
Fixes command `generate spec` to only emit `schema` for parameters `in: body`.
As defined in https://swagger.io/specification/v2/#parameterObject.
=> genspec: use schema only for params in body

codescan/application.go, fixtures/goparsing/classification/models/nomodel.go
This merge requests improves the command `generate spec` as follows:
```go
type (
// Do not ignore this comment block
Foo struct {
}
)
```
```go
// Do not use this comment block for type Foo and Bar
type (
// Use this comment block for type Foo instead
Foo struct {
}
// Use this comment block for type Bar instead
Bar struct {
}
)
```
=> codescan: use TypeSpec.Doc over GenDecl.Doc

codescan/schema.go
My crash for the issue https://github.com/go-swagger/go-swagger/issues/2690 goes away with this little patch.
I am not sure if this fixes the real issue, or if this is just a workaround.
Somebody with more expertise should inspect the patch before applying.
=> avoid nil pointer panic

codescan/schema.go
fixes https://github.com/go-swagger/go-swagger/issues/2704 : strfmt.ObjectId is scanned back as an array of strings
Signed-off-by: Nick Dimov <3619341+dimovnike@users.noreply.github.com>
=> #2704 codescan fix for strfmt.ObjectId

examples/cli/README.md, examples/cli/cli/cli.go, generator/templates/cli/cli.gotmpl
Not all projects use as a base path `/`, and this limitations makes generation of projects with go-swagger difficult to maintain.
Please consider this proposal as a solution to the issue described above.
Possibly related to https://github.com/go-swagger/go-swagger/issues/1083
=> support for passing basepath as an argument

docs/use/template_layout.md, generator/template_repo.go, go.mod, go.sum
Add sprig library for template functions.
Fixes #2737
Alternative to #2738
Removes duplicates from the funcMap that exist already in sprig.
Note that this does leave the `hasPrefix` function overriding the one in
sprig. This is because the sprig function expects arguments of the form
`(prefix, string)` and the existing go-swagger function expects
`(string, prefix)`.
As to not cause a breaking change to the existing templating this was
left as-is.
Signed-off-by: Kevin Barbour <kevinbarbourd@gmail.com>
=> Add sprig library for template functions.

docs/tutorial/composed-auth/README.md, examples/composed-auth/README.md, examples/composed-auth/auth/authorizers.go, go.mod, go.sum
The original repository dgrijalva/jwt-go is no longer maintained and has
a high severity vulnerability (CVE-2020-26160)[1]. There is no patch
available and users of jwt-go are advised to migrate to golang-jwt[2].
This commit updates the library to its latest version.
1. https://nvd.nist.gov/vuln/detail/CVE-2020-26160
2. https://github.com/golang-jwt/jwt
Signed-off-by: Katyanna Moura <amelie.kn@gmail.com>
=> Update jwt library

codescan/parser.go, codescan/routes.go, codescan/routes_test.go, docs/use/spec/route.md, fixtures/goparsing/classification/operations/todo_operation.go, fixtures/goparsing/classification/operations_body/todo_operation_body.go
Adding basic functionality to support the definition of vendor extensions on a per-path basis as requested in issue #1957. This would be defined by a developer within a `swagger:route` block of their codebase, and the corresponding swagger definition would be created when running `swagger generate spec`. These changes currently only support go1.11+.
These changes are making the following assumptions:
- the value of a vendor extension can be a single string, a list/array of strings, or objects
- a list cannot contain a mix of strings and objects
- annotations defining extensions should be indented properly
- each extension key must start with `x-`, e.g. `x-some-extension`
- objects defined in an extension may contain multiple other nested objects
The new extension parser reads through the …
=> 1957: Support for extensions within swagger:route

docs/install.md
`-e GOPATH=$(go env GOPATH):/go` is wrong and should most likely be 
`-e GOPATH=/go -v $(go env GOPATH):/go`
=> Fix docker command in install.md

codescan/application_test.go, codescan/parameters_test.go, codescan/parser.go, codescan/responses_test.go, codescan/schema.go, codescan/schema_test.go, fixtures/goparsing/classification/models/nomodel.go
```go
package main
// swagger:model Example
type Example struct {
MyField map[string]interface{} `json:"my_field,omitempty"`
}
```
should to generate:
```
{
"swagger": "2.0",
"paths": {},
"definitions": {
"Example": {
"type": "object",
"properties": {
"my_field": {
"type": "object",
"additionalProperties": {},
"x-go-name": "MyField"
}
}
}
}
}
```
but currently generates:
```
{
"swagger": "2.0",
"paths": {},
"definitions": {
"Example": {
"type": "object",
"properties": {
"my_field": {
"type": "object",
"additionalProperties": {
"type": "object"
}
"x-go-name": "MyField"
}
}
}
}
}
```
`interface{}` as value in a `map` should be mapped to `any`. This PR fixes this! 
this issue is more described in: #2758
=> fixbug: `interface{}` in a `map` as value should be generated/typed to `any`

cmd/swagger/commands/generate/shared.go, cmd/swagger/commands/generate/sharedopts_nonwin.go, cmd/swagger/commands/generate/sharedopts_win.go, generator/genopts_nonwin.go, generator/genopts_win.go, generator/operation_test.go, generator/shared.go, generator/shared_test.go
This PR adds the ability to use a [go plugin](https://pkg.go.dev/plugin) to add custom functions to the templating library when using custom templates.
In #2741 I added the sprig library to provide some templating functionality we needed for a project, but it may be valuable to have the ability for users to inject their own template functions without modifications to the go-swagger codebase.
Haven't checked that this compiles on Windows yet, and I'd like to write some tests around the plugin functionality itself but wanted to gauge interest and see if something like this could be a valuable contribution to the project. 
Note that plugins are not supported on Windows hence the splitting of the code into files with `windows` and `!windows` build tags.
=> Add support for template plugins

generator/templates/server/server.gotmpl
revised version of https://github.com/go-swagger/go-swagger/pull/2775
When execute `swagger generate support` on the environment without Go and its runtime source,
it will be failed with this messages.
```
2022/05/16 15:47:25 source formatting failed on template-generated source ("restapi\\server.go" for server). Check that your template produces valid code
2022/05/16 15:47:25 unformatted generated source "server.go" has been dumped for template debugging purposes. DO NOT build on this source!
source formatting on generated source "server" failed: err: go command required, not found: exec: "go": executable file not found in %PATH%: stderr:
```
This came from missing packages to imports in the template of server.go.
(the formatter would requrie Go's source code to complete those packages) …
=> made up for missing packages from template

docs/install.md
Fix #2800 
This is similar to https://github.com/caddyserver/dist/issues/83, so I fixed it by adapting their solution. Tested on fresh Ubuntu 22.04 VPS.
=> Fix #2800 Update key import method for debian

codescan/parameters.go, docs/use/spec/params.md
Related to https://github.com/go-swagger/go-swagger/pull/2751.  
For i18n document,  `route` almost can include more information, now I want the `parameter` has more information.
Example
Input:
```go
// swagger:parameters listPets
type FooParam struct {
// Bar parameter in query
// Required: true
// Extensions:
//   x-description-i18n:
//     cn: 一个参数
Bar string `query:"bar"`
}
```
Output:
```go
paths:
"/pets":
get:
parameters:
- description: Bar parameter in query
in: query
name: Bar
required: true
type: string
x-description-i18n:
cn: 一个参数
```
=> Support for extensions within swagger:parameters

.github/workflows/test.yaml, Dockerfile
fixes #2838 
fixes #2841 
fixes #2842
=> build without -trimpath because it causes issues when generating a spec

examples/contributed-templates/stratoscale/restapi/configure_petstore.go, examples/contributed-templates/stratoscale/restapi/operations/pet/pet_create_parameters.go, examples/contributed-templates/stratoscale/restapi/operations/pet/pet_update_parameters.go, examples/contributed-templates/stratoscale/restapi/operations/store/order_create_parameters.go, generator/templates/contrib/stratoscale/server/configureapi.gotmpl
Currently the configuration code generated by the _stratoscale_ templates doesn't allow changing the consumers before creating the handler. This makes it difficult to use custom consumers. For example, we would like to use a JSON consumer that rejects unknown fields. To make that easier this patch changes the templates so that the _Config_ object that is passed to the _Handler_ function has additional fields to specify those custom consumers. With that in place we will be able to do something like this:
```go
// myConsumer is a consumer function that rejects unknown fields.
func myConsumer() runtime.Consumer {
return runtime.ConsumerFunc(func(reader io.Reader, data interface{}) error {
dec := json.NewDecoder(reader)
dec.UseNumber()
dec.DisallowUnknownFields()
return dec.Decode(data)
})
} …
```
=> Configurable consumers in stratoscale templates

fixtures/goparsing/classification/operations/todo_operation.go, scan/routes.go, scan/routes_test.go, scan/scanner.go, scan/schema.go
The tests I added in `scan/routes_test.go` used to fail, because the extensions put in routes weren't being parsed.
This PR fixes those tests - it makes the extensions be properly parsed.
=> fix route extensions not being parsed

examples/contributed-templates/stratoscale/client/pet/pet_client.go, examples/contributed-templates/stratoscale/client/pet/pet_create_responses.go, examples/contributed-templates/stratoscale/client/pet/pet_delete_responses.go, examples/contributed-templates/stratoscale/client/pet/pet_get_responses.go, examples/contributed-templates/stratoscale/client/pet/pet_list_responses.go, examples/contributed-templates/stratoscale/client/pet/pet_update_responses.go, examples/contributed-templates/stratoscale/client/pet/pet_upload_image_responses.go, examples/contributed-templates/stratoscale/client/petstore_client.go, examples/contributed-templates/stratoscale/client/store/inventory_get_responses.go, examples/contributed-templates/stratoscale/client/store/order_create_responses.go, examples/contributed-templates/stratoscale/client/store/order_delete_responses.go, examples/contributed-templates/stratoscale/client/store/order_get_responses.go, examples/contributed-templates/stratoscale/client/store/store_client.go, generator/templates/contrib/stratoscale/client/client.gotmpl, generator/templates/contrib/stratoscale/client/facade.gotmpl
This PR modifies the stratoscale template to make it easier to test.
1. The facade uses the operation group interfaces (API) instead of using the actual client struct. This makes it easy to mock things out during tests.
2. mockery v2 is used instead of mockery v1. Mocks are generated in a mocks package inside the operation group package now instead of the same package. (--keeptree vs --inpackage)
3. Adds the expecter interface to mockery which is preferable and keeps the file casing as underscore to comply with golang file conventions.
=> Make stratoscale template easier to test

fixtures/bugs/2911/fixture-2911.yaml, generator/model_test.go, generator/templates/schemavalidator.gotmpl
Fixes issue #2911 
- a4b8a2de152c56ed58d299d402a4a8e523689035 modifies the model template to add the `swag.IsZero` condition.
- 90c671d3a324075dba949a6f79fb50c851bf4593 adds a small test verifying that the added condition is indeed in the resulting code
=> Skip `ContextValidate` when the field is `nil` avoiding a panic fixing #2911

generator/spec.go
Users can pass in --keep-spec-order to maintain the field order when generating go code. This flag is not actually respected, and fields are generated in alphabetical order. The reason for this is WithAutoXOrder generates a new YAML with x-order set on definition properties, however the new spec YAML is never actually used. This PR fixes this by reloading g.Spec if PropertiesSpecOrder is set.
The bug can be reproduced by running swagger@HEAD against `https://github.com/go-swagger/go-swagger/blob/master/fixtures/codegen/keep-spec-order.yml`, e.g. `swagger generate client --spec keep-spec-order.yml --keep-spec-order`
cc @casualjim
=> Fixes PropertiesSpecOrder not being used

generator/templates/server/builder.gotmpl
If you call a method and pass a non uppercase word as an argument to method, it will inevitably panics because we are not using the same (that we checked when getting) value as the key when setting the value.
=> Fixed panic in AddMiddlewareFor method if method is not uppercase

generator/support_test.go
This PR simplifies tests in `support_test.go` by using `T.TempDir` and `T.Setenv`.
[`T.TempDir`](https://pkg.go.dev/testing#T.TempDir) automatically deletes the temp directory. [`T.Setenv`](https://pkg.go.dev/testing#T.Setenv) restores the env variable after a test.
=> test: use T.TempDir and T.Setenv to simplify code

cmd/swagger/commands/diff/difftypes.go
This PR just adds a new compatibility level warning. Warning should be used for changes which are technically non-breaking but can cause behavior changes on client.
Implements #2932
=> feat(diff): introducing warning compatibility level

.golangci.yml
golangci-lint often exit with code 4, which represents timeout, after PR merge into master.
This is due to the default settings of golangci-lint, [which is 1m](https://golangci-lint.run/usage/configuration/), and timeout option can be set.
In most cases, they're over the time limit slightly, which were just a few seconds, so that I think it's good to pass timeout option and set as 5m as lots of OSS do.
=> fix timeout of golangci-lint

codescan/spec.go
I was reading through your project's code and noticed a small typo in the codescan/spec. 
I've corrected it in this pull request.
=> Fix typo in codescan/spec.go

codescan/schema.go, fixtures/goparsing/spec/api.go
I'd like to support type alias when generating spec.
Changed test will generate spec like this:
```json
"Customer": {
"title": "Customer of the site.",
"$ref": "#/definitions/Customer"
}
```
After adding 3 lines of code, the spec is back to normal.
=> Support type alias when generating spec

generator/operation.go, generator/structs.go
Sometimes we need to give a custom tag to parameters for handling specific needs, such as creating identifier which parameters is used as a pagination filter
=> Add support for x-go-custom-tag in generated parameter

.golangci.yml, cmd/swagger/commands/diff.go, codescan/parameters.go, codescan/parser.go, codescan/responses.go, codescan/schema.go, go.mod, go.sum
* Since Dec 1, 2021, github.com/pkg/errors is an archived project.
* Since go 1.13, there is a standard errors and fmt modules that provides equivalent ways to handle errors.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> use Go standard errors

generator/templates/client/client.gotmpl
This adds a couple constructors for initializing a client WITHOUT having to use the `go-openapi` structs. 
Note: I tried running the tests and most passed, but the build_test.go file that uses the fixtures did not seem to pass. The errors were related to httptransport being undefined. I do have this installed, so not sure why I got this error. I did build the project successfully, so not sure why these errors were occurring? Any guidance appreciated.
=> Feat: new client constructors wo go-openapi

cmd/swagger/commands/expand.go
* contributes #2919
The full fix is provided by https://github.com/go-openapi/swag/pull/75
=> fix(yaml): fixed panic when MarshalYAML returns an error

cmd/swagger/commands/diff/checks.go, cmd/swagger/commands/diff/compatibility.go, cmd/swagger/commands/diff/spec_analyser_test.go, fixtures/bugs/2962/new.json, fixtures/bugs/2962/old.json
A non-required added property in a request should not be reported as a breaking change.
Fixed the change status of added properties depending on being required or not in the new specification.
* fixes #2962
=> fix(diff): fixed diff status on added required property

generator/support.go
This PR allows the generate markdown command to abide by the --target flag like other commands.
* fixes #2938
=> fix(markdown): added support for --target flag

docs/install.md
I was adding instructions on how to install the command line tool to a new project and I was unsure if the cli tool could be installed using `go install`
I worked it out, so adding details on how to install using `go` here
=> Add details on how to install using go install

fixtures/goparsing/petstore/models/order.go
Fixes a little typo in a comment in file fixtures/goparsing/petstore/models/order.go
=> Fixes #2740 - Minimum misspelled

fixtures/bugs/2590/2590.yaml, generator/client_test.go, generator/templates/client/response.gotmpl
As suggested in #2590, this PR replaces
fmt.Sprintf("%+v", somePayloadPossiblyAPointer)
by a JSON representation of the payload
This is only enabled when the response has a Schema and this is not a stream.
* fixes #2590
=> fix(client): alleviates issues with pointers in error reporting

.github/workflows/test.yaml, .golangci.yml
* lint: fixed outdated configuration for linter "depguard" (resulting in many alerts on local testing with the latest version of golangci-lint)
* ci: updated github actions
* ci: use latest golangci-lint
* ci: replace "go1.20" by "oldstable", added go1.21 with "stable" - kept go1.19 for now
=> chore(ci): linter & ci configuration

generator/formats.go, generator/templates/cli/registerflag.gotmpl
Since ULID is now part of go-openapi/strfmt, added support for this format.
* fixes #2467
=> feat(formats): added built-in support for ULID format

fixtures/bugs/2821/ServiceManagementBody.json, generator/model_test.go, generator/template_repo_test.go, go.mod, go.sum
This PR fixes a special case when a "$" is inside a name AND we generate polymorphic types.
In this case the unexported name was not properly generated (included a blank space). More generally, swag mangling functions fail to properly handle this extra blank space. Fortunately, ToGoName wasn't affected and this is why this failure occurs in such rare circumstances.
* requires go-openapi/swag#78
* fixes #2821
=> fix(mangling): fixes name mangling in the presence of a special character

fixtures/bugs/1083/pathparam_test.go, fixtures/bugs/1083/petstore.yaml, generator/generate_test.go
Added a test that constructs a generated client, dynamic untyped server and exercise the stack (in this case, asserting how an escaped path parameter moves across the stack from runtime client to runtime server).
* fixes #1083 (asserts was already working)
=> test(client): added dynamic test to assert path params

generator/client_test.go
Testing client codegen depends somehow on GOPATH.
One test wants to assert how imported packages are generated.
Currently, this works just fine when GOPATH is unset, but on some
older environments, this environment might be set.
This PR makes tests work in both situations (generation is carried out
in different target locations).
=> fixed client generation test re sensitiveness to GOPATH

go.mod, go.sum
* onboards strfmt fix (go-openapi/strfmt#113): replaced regexp-based uuid validations by google/uuid
* fixes #2878
=> fix(strfmt): stricter UUID validation

fixtures/bugs/2604/2604.yaml, generator/model.go, generator/moreschemavalidation_fixtures_test.go, generator/moreschemavalidation_test.go
* fixes #2604
This PR fixes the empty Validate methods generated when generating embedded structs (that is, when an object redefines another object with a $ref).
Since the actual need for validation is not known when hitting the embedded struct, always assume a validation.
Exception: when the embedded type is interface{} or io.Reader, we know that we should not call Validate.
=> fix(validations): fixed missing validation in embedded structs

cmd/swagger/commands/generate/model.go, docs/generate/model.md, fixtures/bugs/2597/2597.yaml, generator/model.go, generator/model_test.go, generator/shared.go, generator/structs.go, generator/template_repo.go, generator/templates/schemavalidator.gotmpl, generator/templates/validation/customformat.gotmpl, generator/templates/validation/maximum.gotmpl, generator/templates/validation/minimum.gotmpl, generator/templates/validation/multipleOf.gotmpl, generator/templates/validation/primitive.gotmpl, generator/utils_test.go
This new option to generate models allows to report more context
in validation errors for arrays and maps.
Validation errors used for those types used to be reported with an
empty path (e.g. " in body should have at least 1 items").
With this option enabled, generated models for arrays and maps
report the type (e.g. "[myArray] in body should have at least 1 items").
This flag acts as a feature flag: it is disabled by default with no
alteration of the existing generated code.
* fixes https://github.com/go-swagger/go-swagger/issues/2597
=> feat(validation): added --rooted-error-path to generate models

fixtures/bugs/2587/2587.yaml, fixtures/enhancements/2163/fixture-2163.yaml, fixtures/enhancements/2444/fixture-2244.yaml, generator/model.go, generator/moreschemavalidation_fixtures_test.go, generator/moreschemavalidation_test.go, generator/structs.go, generator/templates/docstring.gotmpl, generator/templates/schemavalidator.gotmpl, generator/templates/validation/structfield.gotmpl
* fixes #2587
This PR fixes some cases in which the Min/MaxProperties were wrongly evaluated:
* case of a property which is a map (issue #2587)
* case of a property which is an array  (non reported issue)
* edge case of a map representing an object with additionalProperties: false and a enum validation
Other fixes:
* fixed duplicate or missing Min/MaxProperties documentation in docstrings
* whenever a min/maxProperties validation is present, if no additional properties key is provided, assume "additionalProperties: true"
* Tests
* added more assertions for existing test cases involving min/max properties (#2444, #2163)
* added codegen assertions with an extended version of the spec provided with issue #2587
This PR introduces some context to GenSchema, namely IsElem and IsProperty, to …
=> fix(validations): fixed MinProperties/MaxProperties

generator/build_test.go, generator/client_test.go, generator/debug_test.go, generator/discriminators_test.go, generator/enum_test.go, generator/generate_test.go, generator/internal/gentest/doc.go, generator/internal/gentest/testutils.go, generator/model.go, generator/model_test.go, generator/moreschemavalidation_test.go, generator/shared.go, generator/shared_test.go, generator/spec_test.go, generator/template_repo_test.go, generator/types_test.go, generator/utils_test.go
This PR generalizes the discarding of log output.
A few rough edges remain (but were previously there), as it is still possible that the few tests that assert the logged output cross the way of a test that discards it.
At least, running tests now generates less clutter.
=> chore(test): reduced the verbosity of tests

fixtures/bugs/2773/2773.yaml, generator/client_test.go, generator/media.go, generator/media_test.go, generator/operation.go, generator/structs.go, generator/support.go, generator/template_repo.go, generator/templates/client/client.gotmpl
* fixes https://github.com/go-swagger/go-swagger/issues/2773
1. fix: no longer sort producers and consumers
The client runtime picks the first one, so the order is relevant.
2. feat: added extra options to set media type
For client codegen only, AND whenever a single group of operations
deals with more than one media for producers OR more than one media
for consumers , THEN we generate an extra set of convenience ClientOption
functions to switch media type.
Generates generic options to set the mime as an arbitrary string
(comes in handy to set mime extensions):
WithContentType(string) (to negotiate consumers)
WithAccept(string) (to negotiate producers)
Generate shorthands with a mangled name such as:
`WithContentTypeApplicationxWwwFormUrlencoded`
to be used directly as an option.
* Simple …
=> feat(gen client): added support to work with multiple mimes

.github/dependabot.yml, .github/workflows/codeql.yml, .github/workflows/scorecard.yml, .github/workflows/test.yaml, Dockerfile, Dockerfile.alpine.ci, Dockerfile.ci, Dockerfile.dev, README.md
CodeQL and OSSF scorecard are both complementary tools useful to detect vulnerabilities.
They also provide help on how to fix them.
There is also a score to publish on the readme.md
This PR includes the pin of GitHub Action and Docker images .
It also provides dependabot config for them as it is not easy to keep track of those hash manually. 
Also using an updater is preconised by ossf.
I didn't configured it for go mod as it is the object of another PR
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> ci: setup ossf scorecard and codql workflows

.github/workflows/test.yaml, hack/build-docker.sh
* fixed coverage reports (junit xml files not consumed by codecov and
flagged as invalid reports)
* adopted go1.20 coverage instrumentation for integration tests
(see https://go.dev/doc/build-cover)
* tried to rationalize the combinatorial headache of platforms x go versions
* redefined our CI workflows as follows:
1. lint
2. build: replaces fka sanity-check, e.g. basic build & run on a large
set of platforms
3. test: run unit tests & report coverage, on 3 platforms and the 2
most recent go versions
4. codegen_test: run swagger command line on a large spectrum of specs
and options. Matrix is a follows:
* os: linux only
* go versions: 2 most recent only
* fixtures scope: 2 sets (large set including various test
fixtures, smaller set with big, popular "canary" specs)
Codegen build is …
=> chore(ci): refactored ci workflows

fixtures/bugs/2866/2866.yaml, generator/generate_test.go, generator/operation.go
* fixes #2866
This PR addresses that case when tags used to generate a package to hold a group of operations are of the special form v[0-9]+.
This form is interpreted by go imports so that "x/v1" resolves as "x" in the program.
To fix the problem, "v[nnn]" package names are renamed "version[nnn]".
=> fix(codegen): fixed operation package mangling when tag is v1

fixtures/bugs/2700/2700.yaml, generator/support_test.go, generator/template_repo.go, generator/templates/markdown/docs.gotmpl
* fixes #2700
This PR introduces a new template function to replace new lines (or carriage returns) in descriptions by "</br>" tags in the generated markdown.
I could verify that this renders correctly on github markdown.
=> fix(markdown): handled multi-lines blocks in descriptions

fixtures/bugs/2650/2650.yaml, generator/template_repo.go, generator/templates/cli/cli.gotmpl, generator/templates/cli/operation.gotmpl, generator/templates/cli/schema.gotmpl
* fixes #2650
This PR reduces the likelihood of name conflicts, by preventing generated names to be sensitive to the "same prefix" syndrome (e.g. Group + "Name" conflicts with "GroupName").
* Also reduced the amount of input-sensitive local var names, when this is not necessary.
* Tried to lighten a bit the template by handing over naming conventions to a template function.
* testing: tested manually. It seems that CLI generation is not subject to any unit tests, so not adding more with this one.
=> fix(cli): deconflicted names for variables and funcs

.codecov.yml, .hound.yml
Codecov sometimes messes up with coverage calculations and I found it frustrating to have failing PRs because of a (fictious) -0.03% coverage degradation.
* Also removed the configuration for an ooooold linter that this repo adopted years ago. No longer in use.
=> ci: added tolerance threshold on codecov reports

.golangci.yml, codescan/meta_test.go, codescan/parser_go119_test.go, codescan/parser_test.go, codescan/responses_test.go, codescan/routes_test.go, codescan/schema_go118_test.go, codescan/schema_test.go, generator/client_test.go, generator/discriminators_test.go, generator/language_test.go, generator/model_test.go, generator/operation_test.go, generator/schemavalidation_test.go, generator/server_test.go, generator/shared_test.go, generator/spec_test.go, generator/template_repo_test.go
Helps follow best practices with testify use.
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
=> golangci-lint: enable testifylint linter

cmd/swagger/commands/diff/spec_analyser.go, fixtures/diff/response.diff.txt, fixtures/diff/response.v1.json, fixtures/diff/response.v2.json
=> record adding and removing schema from response in swagger diff #3074

docs/use/spec/route.md
A few typos have been fixed directly by patching the generated html in go-swagger/go-swagger.github.io.
This PR resyncs the original source markdown.
=> doc: sync'ed doc source with website

.github/workflows/test.yaml
With codecov action v4, the "tokenless" functionality works but is somewhat deprecated.
With codecov action v3 or v4, even with tokenless support, our CI sometimes fails because codecov hits a rate limit on github API.
The safest way to securely send our test coverage without failures is to configure the token as a github action secret and use that token to connect to codecov.
=> ci: reenacted codecov secret token

go.mod, go.sum
When merging #3073, a test-only replace clause in go.mod has splipped in, preventing proper go-gettability. This PR restores a clean go.mod.
=> fix(deps): fixed undue go.mod replace

.github/workflows/test.yaml
From time to time, CI fails because of codecov being too slow to process uploads. This has become more and more frequent as of late.
Reference: https://github.com/codecov/codecov-action/issues/926
Proposed workaround: wrap the action with a retry. 30s seems the delay recommended by codecov.
=> ci: added retries on codecov coverage report upload

generator/model.go, generator/model_test.go, generator/structs.go, generator/templates/structfield.gotmpl, generator/types.go, generator/util.go
Go-swagger would generate duplicated tags while using the `x-go-custom-tag` extension.
for example:
```
properties:
tags:
items:
type: string
type: array
x-go-custom-tag: '"json:",inline"'
```
The output looks like this:
```
Tags []string `json:"tags" json:",inline"`
```
After this PR merged, the output will be:
```
Tags []string `json:",inline"`
```
=> fix: duplicated tags when using `x-go-custom-tag` extension

.github/workflows/test.yaml
The CI checkout in pull requests was checking out the master branch, which made it easy to miss the issues in tests and to push changes with test issues to master, because these issues were not seen in the PR
I added
```
with:
ref: ${{ github.head_ref }}
```
into every job that is lint/test/build related, not sure if we need it in the docker jobs
I will address the issues with tests in the next PR
cc @casualjim
=> fix(CI/tests): checkout the PR commits, not master

.github/workflows/test-pr.yaml, .github/workflows/test.yaml
Second try, I'm moving out the PR action in it's own file and adding the solution for forks from https://github.com/actions/checkout/issues/551
The reason the previous one is failing is the fact that the commit from the fork doesn't actually exist in this repo
Reverted the changes from the previous commit in `test.yaml` that from now on should be only triggered on master/tag builds
@casualjim let's try this again, hopefully it works this time around.
And thank you for helping out with the merges
=> fix(ci): checkout action fix & move out pr pipeline

.github/workflows/test-pr.yaml
My recent changes to the PR CI pipeline trigger a critical issue on the OpenSSF Scorecard
Related to: https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
And 
```
ref: ${{ github.event.pull_request.head.ref }}
repository: ${{ github.event.pull_request.head.repo.full_name }}
```
Basically, the issue being, we should not give the code from the forks any write permissions to the repo and any access to the secrets, which `pull_request_target` seems to provide
Changing the `pull_request_target` to `pull_requst` as it has less permissions, also removing write permissions and secrets from the PR workflow
Pull request CI ran without issues in this PR, see the jobs with (pull_request) suffix
I'm going to create and close two more test PR's that are supposed to test the …
=> fix(ci): fix codeql security issues

.github/workflows/scorecard.yaml
Fixing one more github workflow:
> Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`.
> Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
`actions/upload-artifact@v3` is deprecated, use `actions/upload-artifact@v4`
Example of a successful run in the fork: https://github.com/nikolaiianchuk/go-swagger/actions/runs/13315910532/job/37189735413
=> fix(ci/scorecard): update upload-artifact to v4

fixtures/bugs/3143/3143.yaml, generator/generate_test.go, generator/operation.go
* Fixes #3143
TL,DR:
* tags like "v[nnn]" should generate "version[nnn}" packages
* but anything that matches "*v[nnn]*" doesn't need to be rewritten
=> Fix replacement of generated packages with a version

docs/faq/faq_server.md
Commit b44601d48a17c24dc821681ded1b6465ddb5f918 moved the location of the `template_layout.md` file. This PR adjusts sources to changes.
=> fix the template layout reference

cmd/swagger/commands/generate/spec.go, cmd/swagger/commands/generate/spec_test.go, cmd/swagger/completion/swagger.zsh-completion, codescan/application.go, codescan/parameters.go, codescan/responses.go, codescan/schema.go, codescan/schema_test.go, docs/generate-spec/_index.md, fixtures/enhancements/pointers-nullable-by-default/item.go
Introduce a new command-line parameter for "generate spec" allowing to set "x-nullable: true" by default for each Go field having a pointer type and not having JSON 'omitempty' option set
=> Introduce a new command-line parameter for "generate spec"

generator/types.go, go.mod, go.sum
The github.com/mitchellh/mapstructure package is archived and no longer receives updates[^1]. The "blessed" fork[^2] is
github.com/go-viper/mapstructure. The API is the same, so nothing needs to be changed apart from the import path.
[^1]: https://github.com/mitchellh/mapstructure/issues/349
[^2]: https://gist.github.com/mitchellh/90029601268e59a29e64e55bab1c5bdc
=> Migrate to github.com/go-viper/mapstructure/v2

generator/utils_test.go
Issue: N/A
**Context**
I'm working on https://github.com/go-swagger/go-swagger/discussions/3190 and found some file and line information in test are not useful enough. Calling [`t.Helper()`](https://pkg.go.dev/testing#T.Helper) should improve them.
**Further candidates to add t.Helper()**
There are more test utilities but I'm not sure whether they make sense to add `t.Helper()`.
<details><summary>examples</summary>
- https://github.com/go-swagger/go-swagger/blob/a70901f095da9244f76cc954596e92bb79d88f17/codescan/schema_test.go#L1121-L1131
- https://github.com/go-swagger/go-swagger/blob/a70901f095da9244f76cc954596e92bb79d88f17/codescan/schema_test.go#L1133-L1137
- https://github.com/go-swagger/go-swagger/blob/a70901f095da9244f76cc954596e92bb79d88f17/codescan/schema_test.go#L1139-L1151
- …
=> add t.Helper() for test utilities

docs/usage/generate.md
Fix typo "operaion" to "operation" in `docs/usage/generate.md`
=> fix: correct typo in generate.md

generator/media.go
Hello,
It's a PR to have csv producer and consumer to avoid this kind of block inside `configure_xxxx_api.go`:
```go
api.CsvProducer = runtime.ProducerFunc(func(w io.Writer, data interface{}) error {
return errors.NotImplemented("csv producer has not yet been implemented")
})
```
and rather have
```go
api.CsvProducer = runtime.CSVProducer()
```
Thx !
=> feat: add csv consumer and producer

docs/reference/annotations/ignore.md
The example for `swagger:ignore` incorrectly included a space, which is not recognized by the parser. This commit removes the space to match the actual behavior of the tool.
=> docs: correct example for swagger:ignore annotation

.github/workflows/test-pr.yaml, .github/workflows/test.yaml
Issue: #3220 (This PR is just a temporal workaround. Doesn't resolve the real issue)
Related comment: https://github.com/go-swagger/go-swagger/pull/3195#issuecomment-3225987022
=> Pin go version on CI as a workaround of #3220
