go-swagger/go-swagger

generator/operation.go
We could not the change (issue #25) that fixes issue #28.
Here is a small fix that does it.
If this is a duplicate, then just close it.
Thanks,
@maximilien and @midoblgsm
=> Fixing package and target order

README.md
=> Some space

httpkit/client/runtime.go, spec/analyzer.go, swag/path_test.go
replaced some hardcoded ":" to Listseparator and changed some filepath to path (slash path)
=> fix test failing on windows.

generator/templates/server/builder.gotmpl, generator/templates/server/configureapi.gotmpl, generator/templates/server/main.gotmpl
Added a shutdown hook in main. It can be assigned to the newly created variable in the xxxAPI struct during configuration. The parameter is preinitialized for backwards compatibility comaptibility reasons.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/go-swagger/go-swagger/pull/199%23issuecomment-170052260%22%2C%20%22https%3A//github.com/go-swagger/go-swagger/pull/199%23issuecomment-170067151%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/go-swagger/go-swagger/pull/199%23issuecomment-170052260%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Forgot%20signed-off-by%20message%22%2C%20%22created_at%22%3A%20%222016-01-08T16%3A47%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3 …
=> Proposed solution to Issue #198

strfmt/default.go, strfmt/duration.go, strfmt/format.go, strfmt/format_test.go
Signed-off-by: Mihail Stoykov <M.Stoikov@gmail.com>
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/casualjim%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/go-swagger/go-swagger/pull/200%23issuecomment-170584754%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-01-11T15%3A18%3A57Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/casualjim%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A …
=> FIXES #193

generator/bindata.go, generator/templates/client/parameter.gotmpl
Fixes #201
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/casualjim%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/go-swagger/go-swagger/pull/202%23issuecomment-170733237%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-01-11T23%3A39%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/casualjim%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/go-swagger/ …
=> generator: Take address of default params for non-required, parameters with defaults

generator/templates/server/builder.gotmpl, generator/templates/server/configureapi.gotmpl, generator/templates/server/main.gotmpl, swag/util.go
Added possibility for custom command line option parsing as agreed upon in #207.
Closes #207
Signed-off-by: Tobias Theobald <tobitheo@gmail.com>
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/casualjim%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/go-swagger/go-swagger/pull/208%23issuecomment-171363159%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-01-13T16%3A57%3A08Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/456109%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/casu …
=> Added possibility for custom command line option parsing

httpkit/request.go, httpkit/request_test.go
=> allow delete requests to have bodies

client/client.go, cmd/swagger/commands/generate/client.go, generator/bindata.go, generator/client.go, generator/operation.go, generator/shared.go, generator/support.go, generator/templates/client/client.gotmpl, httpkit/client/runtime.go
=> Use schemas consumes to determine accept headers

client/client.go, cmd/swagger/commands/generate/client.go, generator/bindata.go, generator/client.go, generator/operation.go, generator/shared.go, generator/support.go, generator/templates/client/client.gotmpl, httpkit/client/request.go, httpkit/client/request_test.go, httpkit/client/runtime.go
Based on top of my PR #236, can separate out if necessary
=> httpkit/client: Only set the content-type if the body isnt empty

spec/swagger.go, spec/swagger_test.go
Signed-off-by: Tom Pytleski <pytlesk4@gmail.com>
Closes #268
=> Add Support for Extensions on the swagger root object.

httpkit/client/request.go
This patch sets the content length of the request or else a chunked transfer is declared, and this corrupts outgoing payloads. the content's length must be set prior to the body being written per the spec at https://golang.org/pkg/net/http
If Body is present, Content-Length is <= 0 and
TransferEncoding hasn't been set to "identity", Write
adds "Transfer-Encoding: chunked" to the header. Body
is closed after it is sent.
To that end a temporary buffer, b, is created to produce the payload body, and then its size is used to set the request's content length.
=> Bugfix for POST Ops not setting Content Length

cmd/swagger/commands/version_number.go, generator/shared.go, generator/shared_test.go, scan/meta.go
This can double as preparation for generating tests
=> ensure file names don't end with _test

generator/support.go
=> Add tar, gzip support

fixtures/goparsing/petstore/rest/handlers/pets.go, scan/scanner.go
=> scan: treat error primitive as string

spec/expander.go, spec/spec.go, spec/swagger.go
@casualjim let me know what you think!
=> - expand schemas properly, with all tests passing.

fixtures/expansion/circularRefs.json, fixtures/expansion/clickmeter.yaml, spec/expander.go, spec/expander_test.go
=> fix Panic expanding responses that are a schema ref with circular

circle.yml
=> increase circle ci default timeout

httpkit/validate/values.go, httpkit/validate/values_test.go
Function `Required` had, I suppose, not desired behaviour due to not correct usage of `reflect` package.
Also I added some tests to `validate` package because there were not that many of them.
=> Add validation required fix and corresponding package tests

fixtures/bugs/465/swagger.yml, generator/operation_test.go, generator/support.go
This fixes the issue, but I'd like to know a good place to put a test for this (or modify an existing test).
In addition, I'm opening the PR so I know the existing test-suite passes because
1) I couldn't find instructions on how to run all tests locally
2) The Circle process I ran on my fork failed - https://circleci.com/gh/nikhilm/go-swagger/3
=> Use spec BasePath when it is non-empty.

README.md, fixtures/goparsing/classification/models/nomodel.go, generator/typeresolver_test.go, generator/types.go, scan/schema_test.go, vendor/github.com/go-openapi/strfmt/default.go, vendor/manifest
Signed-off-by: Todd Neal <todd@tneal.org>
=> Add support for strfmt.MAC

generator/server_test.go, generator/support.go, vendor/github.com/go-openapi/errors/schema.go
=> Fix typo mulit vs multi

cmd/swagger/commands/version_number.go, vendor/github.com/willf/bitset/LICENSE, vendor/github.com/willf/bitset/bitset.go, vendor/github.com/willf/bitset/popcnt.go, vendor/github.com/willf/bitset/popcnt_amd64.go, vendor/github.com/willf/bitset/popcnt_amd64.s, vendor/github.com/willf/bitset/popcnt_generic.go, vendor/manifest
=> adds bitset library

cmd/swagger/commands/version_number.go, fixtures/goparsing/classification/models/extranomodel.go, fixtures/goparsing/classification/transitive/mods/aliases.go, generator/bindata.go, scan/parameters.go, scan/responses.go, scan/routes_test.go, scan/scanner_test.go, scan/schema.go, scan/schema_test.go
=> handle aliased types in scanner

fixtures/bugs/540/swagger.yml, generator/bindata.go, generator/response_test.go, generator/templates/server/responses.gotmpl
=> Don't include indirection for interface types.

fixtures/goparsing/classification/operations/noparams.go, fixtures/goparsing/classification/operations/responses.go, scan/parameters.go, scan/parameters_test.go, scan/responses.go, scan/responses_test.go, scan/schema.go
Following on from #617... turns out this was done in 3 places, so I've yanked it out into its own parsing function and added more tests for blank names in JSON tags.
Looks like there's some more duplication and refactoring that can be done here, but I suppose this is a good start.
=> Refactor JSON tag parsing

cmd/swagger/commands/version_number.go, generator/bindata.go, hack/devtools.sh, scan/parameters.go, scan/responses.go, scan/schema.go
closes #608 
closes #623 
related #241
=> Scan package

generator/templates/server/server.gotmpl
Replace mentions of "todo list" with actual name
=> Fix up server logs

generator/bindata.go, generator/templates/schematype.gotmpl, generator/templates/structfield.gotmpl
=> Make the template for schematype and structfield  more readable.

circle.yml, generator/shared.go
=> normalize the filename to honor skip_exists config property

cmd/swagger/commands/generate/model.go, cmd/swagger/commands/generate/operation.go, generator/bindata.go, generator/model.go, generator/operation.go
=> fix model and operation generator command

fixtures/goparsing/petstore/models/pet.go, fixtures/goparsing/petstore/rest/handlers/pets.go, scan/parameters.go, scan/responses.go, scan/scanner_test.go, scan/schema.go
Fixes #694
Parses out swagger:strfmt on struct properties
=> Parse embedded swagger:strfmt tags

cmd/swagger/commands/generate/spec.go, generator/bindata.go
=> add a --compact flag and pretty print by default

fixtures/codegen/todolist.allparams.yml, generator/bindata.go, generator/parameter_test.go, generator/shared.go, generator/template_repo.go
=> mangle var names

generator/bindata.go, generator/model_test.go, generator/templates/structfield.gotmpl
=> don't use omitempty on array fields

fixtures/goparsing/classification/models/nomodel.go, fixtures/goparsing/classification/operations/responses.go, scan/responses.go, scan/responses_test.go, scan/schema.go, scan/schema_test.go
=> Adds support for `[]*Foo` to the other types

generator/templates/schemavalidator.gotmpl, generator/templates/server/parameter.gotmpl
Reverts go-swagger/go-swagger#792
This is a breaking change on a public interface, needs more thought
=> Revert "fix #767: field-name-not-showing-if-using-ref"

fixtures/bugs/789/swagger.yml, generator/operation_test.go, vendor/github.com/go-openapi/validate/slice_validator.go, vendor/github.com/go-openapi/validate/spec.go, vendor/manifest
=> add test for issue 789

docs/generate/spec/operation.md, docs/generate/spec/route.md, fixtures/enhancements/793/petstore.go, fixtures/goparsing/classification/operations_annotation/operations.go, scan/classifier.go, scan/classifier_test.go, scan/operations.go, scan/operations_test.go, scan/path.go, scan/routes.go, scan/scanner.go, scan/scanner_test.go
=> add operation annotation

vendor/github.com/go-openapi/loads/spec.go, vendor/github.com/go-openapi/spec/expander.go, vendor/github.com/go-openapi/spec/ref.go, vendor/github.com/go-openapi/validate/result.go, vendor/github.com/go-openapi/validate/spec.go, vendor/manifest
=> validate respects local file reference

generator/support.go
=> allow for gopath to be differently cased from actual

docs/generate/spec/response.md, docs/generate/spec/route.md
=> make sure docs and its inline example match

fixtures/goparsing/classification/operations/noparams.go, fixtures/goparsing/classification/operations/responses.go, scan/parameters.go, scan/parameters_test.go, scan/responses.go, scan/responses_test.go
=> Fixes #896 - Added *ast.StarExpr to parsers

docs/generate/client.md, docs/generate/server.md, docs/generate/spec.md
The usage for the generate commands were out of date. Updates to both
the client and server usage, along with consistent format for both.
=> Task: Update generate docs

scan/parameters_test.go, scan/responses_test.go, scan/schema.go, scan/schema_test.go
=> no x-go-name on $ref props

fixtures/bugs/987/swagger.yml, generator/server_test.go
=> verify nested consumer/producer

fixtures/bugs/1010/swagger.yml, generator/operation.go, generator/parameter_test.go
=> varname value expression for param items

generator/template_repo.go
Hi, I want to add some template to default registry but didn't find how to do it. This PR have to solve this issue. Is it a correct solution or we have some different way for this?
=> helper function for extending a default repositiry of templates

generator/operation.go, generator/structs.go
Expose vendor extensions for parameters, responses and operations to template for custom implementations.
=> Expose extensions

docs/use/template_layout.md
Hi, thank you for providing awesome library.
I probably found a mistake of a configuration in the example template.
Please take a look.
=> Fix the example template of default-server.

fixtures/goparsing/classification/models/nomodel.go, scan/schema.go, scan/schema_test.go
The problem is described in #1102
=> Ignored overriden fields fix #1102

cmd/swagger/commands/generate/model_test.go
Adds test for model generation via command
=> Test model generator

docs/use/template_layout.md
fix a typo in layout description
=> fix a typo in layout description

Gopkg.lock, vendor/github.com/go-openapi/validate/spec.go, vendor/github.com/go-openapi/validate/values.go, vendor/github.com/go-openapi/validate/values_test.go
In response to update of validate package in go-openapi. #890
=> Updates vendor dep for go-openapi/validate

docs/generate/server.md
Minor doc change configure_xxx.go
=> Minor doc change configure_xxx.go

scan/classifier.go, scan/scanner.go, scan/schema.go
=> 1. supported custom swagger data type #1183

generator/types.go
We could use custom x-* fields in models
=> Add extensions available for models

examples/2.0/petstore/server/api/petstore.go
=> remove petstore panic

generator/model.go
=> handle model property conflicts when format is "date" or "datetime"

fixtures/goparsing/classification/models/nomodel.go, scan/schema.go, scan/schema_test.go
=> handle time.Time properly during parsing go source files

cmd/swagger/commands/generate/shared.go, docs/generate/client.md, docs/generate/server.md
Small issues, small fixes... Moving forward and learning.
=> Fix issue#1263

cmd/swagger/commands/generate/client.go, cmd/swagger/commands/generate/model_test.go, cmd/swagger/commands/generate/operation.go, cmd/swagger/commands/generate/server.go, cmd/swagger/commands/generate/support.go, cmd/swagger/swagger.go, generator/client.go, generator/model.go, generator/model_test.go, generator/operation.go, generator/operation_test.go, generator/server_test.go, generator/shared.go, generator/shared_test.go, generator/support.go, generator/support_test.go
#1272 
Improve error handling while generating templates.
=> fix #1272 - Improve error handling in generator

Gopkg.lock, vendor/github.com/go-openapi/spec/operation.go
=> bump go-openapi/spec

cmd/swagger/commands/validate_test.go, fixtures/bugs/1238/swagger.yaml
Added fixture following confirmation that go-swagger/go-swagger#1238 has been fixed (items on objects).
=> 1238-fix: add fixture in UT 

Gopkg.lock, vendor/github.com/go-openapi/spec/expander.go
See issue https://github.com/go-swagger/go-swagger/issues/1331
A commit would also be required in the vendor sub-directory; I'm not sure how you manage the commits for the vendor sub-directory.
=> 1331 - Delete temporary files

generator/shared.go
=> Fixed dump-data as json

cmd/swagger/swagger.go, docs/SUMMARY.md, docs/usage/serve_ui.md, docs/usage/swagger.md, docs/usage/validate.md
=> Add quiet mode and output redirection

fixtures/bugs/1198/fixture-1198.yaml, generator/model_test.go
Signed-off-by: Greg Marr <greg.marr@autodesk.com>
=> Add test for #1198 which was fixed with #1397

fixtures/bugs/909/fixture-1414.json, fixtures/bugs/909/gen-fixtures.sh
Extended non-regression testing for parameters codegen, following PR #1394
=> Added test case from issue#1414 as fixture

fixtures/codegen/issue-1066.yaml, fixtures/codegen/issue-1388.yaml, fixtures/codegen/issue-984.yaml, fixtures/codegen/swagger-gsma.json, hack/codegen-nonreg.sh
- fixes #1388
- fixes #1066
- fixes #984
- fixes #951
=> Added codegen fixtures to acknowledge fixed issues.

fixtures/bugs/1437/fixture-1437-2.yaml, fixtures/bugs/1437/fixture-1437-4.yaml, fixtures/bugs/1437/gen-fixtures.sh, generator/model.go, hack/codegen-nonreg.sh
* prevents format validation to bubble up in a composition of a primitive type
=> Fixing #1437 uncovered another issue on type aliasing.

doc.go, fixtures/bugs/1277/.gitignore, fixtures/bugs/1277/cloudbreak.json, fixtures/bugs/1277/fixture-1277.json, fixtures/bugs/1277/gen-fixtures.sh, hack/codegen-nonreg.sh
* fixes #1277 (circular $ref)
Please note that the cloudbreak.json spec is still not fully supported (see fixture).
=> Acknowledge bug fixes and add CI fixtures.

docs/faq/faq_documenting.md, docs/faq/faq_model.md, docs/faq/faq_server.md, docs/faq/faq_spec.md
Updated FAQ in docs, with content gathered from "question" issues.
Corresponding issues may be now closed:
- fixes #997
- fixes #1334
- fixes #1029
- fixes #1375
=> FAQ update

generator/client.go, generator/structs.go, generator/support.go
Add GenOpts to GenOperationGroup and align this Generator with others.
=> Extend gen operation group

fixtures/bugs/1513/enums.yaml, generator/parameter_test.go, generator/templates/client/parameter.gotmpl
=> fix writing enum parameters (#1513)

fixtures/bugs/1487/fixture-moreAddProps.yaml, fixtures/bugs/1487/gen-fixtures.sh, generator/model.go, generator/moreschemavalidation_fixtures_test.go, generator/moreschemavalidation_test.go
- fixes codegen on anonymous complex additional properties (e.g. with --skip-flatten)
- extends UT in expand mode
=> Fix complex anonymous additional properties

.github/CONTRIBUTING.md, docs/SUMMARY.md, docs/guidelines/README.md
=> Document contribution guidelines

fixtures/bugs/1646/fixture-1646.yaml, generator/operation_test.go, generator/support.go
=> fix random ordering of mimetypes in the doc strings on generate

fixtures/bugs/931/.gitignore, fixtures/bugs/931/fixture-931.yaml, fixtures/bugs/931/gen-fixtures.sh, hack/codegen-nonreg.sh
=> Acknowledges fix from previous PR (#1160) - added test to CI

fixtures/bugs/1596/.gitignore, fixtures/bugs/1596/fixture-1596.yaml, fixtures/bugs/1596/gen-fixtures.sh, generator/shared.go, generator/shared_test.go, generator/template_repo.go, generator/template_repo_test.go
This includes all GOOS, GOARCH and "_test"
* fixes #1596
=> Mangle file names with a specific meaning for go build

examples/oauth2/README.md, examples/oauth2/restapi/configure_oauth_sample.go, examples/oauth2/restapi/implementation.go
Better example code re question #1629
=> Better example for redirect in operation

generator/moreschemavalidation_test.go
This fixes (again!) the t.Parallel() issue in schema validation unit tests.
The critical section which must be protected by locks is longer than initially thought,
because of package level cache in go-openapi/spec.
=> Fix race condition in unit test

docs/use/spec.md
Enhance spec to reflect swagger CLI usage for the yaml generation and avoid generating Go language extension
=> Enhance spec 

generator/model.go, generator/structs.go, generator/support.go, generator/types.go
=> Fix do not generate models with x-go-type extension

fixtures/bugs/1746/fixture-1746.yaml, generator/server_test.go, generator/support.go
=> Fix go generate command when --name is absent

docs/guidelines/README.md
=> Updated contributing guidelines

fixtures/goparsing/classification/operations_annotation/operations.go, scan/operations_test.go
=> verifies swagger:operation can deal with $ref

docs/use/spec.md
Simple fix typo in doc . 
change sepc to spec
=> fix typo in docs

docs/guidelines/README.md, generator/debug.go, generator/debug_test.go, generator/model.go, generator/types.go
=> Fix go vet 11 issue with debugAsJSON func

generator/client.go, generator/model.go, generator/operation.go, generator/server_test.go, generator/shared.go, generator/shared_test.go, generator/support.go
=> Fixed go generate paths in configure_xxx.go

fixtures/bugs/1839/.gitignore, fixtures/bugs/1839/fixture-1839-mini.yaml, fixtures/bugs/1839/gen-fixtures.sh, generator/model.go, hack/codegen-nonreg.sh
Models: avoids redundant "()" on .ValueExpression when using polymorphic type
* fixes #1839
=> Models: avoids redundant "()" on .ValueExpression

docs/use/spec/model.md, fixtures/goparsing/classification/models/nomodel.go, scan/schema.go, scan/schema_test.go
=> Add support for property extensions

fixtures/goparsing/classification/operations/responses.go, fixtures/goparsing/classification/operations/todo_operation.go, scan/responses_test.go
Just increase test coverage involved prev. pull request.
=> test coverage increase

fixtures/codegen/keep-spec-order.yml, generator/model_test.go, generator/support.go
Signed-off-by: kofler <efi.kofler@flir.com>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/go-swagger/go-swagger/1968)
=> keep spec order on nested objects

fixtures/bugs/1020/.gitignore, fixtures/bugs/1020/fixture-1020.yaml, fixtures/bugs/1020/gen-fixtures.sh, fixtures/bugs/1339/.gitignore, fixtures/bugs/1339/fixture-1339.yaml, fixtures/bugs/1339/gen-fixtures.sh, fixtures/bugs/1490/.gitignore, fixtures/bugs/1490/fixture-1490.yaml, fixtures/bugs/1490/gen-fixtures.sh, fixtures/bugs/973/.gitignore, fixtures/bugs/973/fixture-973.yaml, fixtures/bugs/973/gen-fixtures.sh, generator/operation_test.go, generator/parameter_test.go, hack/codegen-nonreg.sh
This PR adds some more tests to acknowledge the following:
* Fixes #1490 
* Fixes #973 
* Fixes #1020
=> acknowledge various fixes for client

codescan/schema.go
=> skip fields when they are not exported

codescan/application.go, codescan/application_test.go, codescan/parameters.go, codescan/responses.go, codescan/responses_test.go, fixtures/goparsing/classification/operations/noparams.go, fixtures/goparsing/classification/operations/responses.go
=> consider maps as valid body for response and parameter

codescan/application_test.go, codescan/parameters.go, codescan/parameters_test.go, codescan/responses.go, codescan/responses_test.go, fixtures/goparsing/classification/operations/noparams.go, fixtures/goparsing/classification/operations/responses.go
=> also consider interface as valid body for response and request

cmd/swagger/commands/generate/spec_go111.go, codescan/application.go, codescan/parser.go, codescan/spec.go
Signed-off-by: Gregory Hill greg.hill@monax.io
Closes #2023
=> enable explicit gen spec inclusion / exclusion or for all deps

cmd/swagger/commands/generate/spec_go111.go, codescan/parser_test.go
Signed-off-by: Gregory Hill <greg.hill@monax.io>
=> fix typo and add more parser tests

codescan/parameters.go, codescan/schema.go, codescan/schema_test.go, fixtures/goparsing/classification/models/nomodel.go
=> fixes detecting base64 for []byte

generator/model_test.go, generator/moreschemavalidation_test.go, generator/operation.go, generator/parameter_test.go, generator/support_test.go
=> Fixed the few remaining linting issues in generator package

examples/todo-list/restapi/server.go
=> regenerated examples with v0.21.0

.circleci/config.yml, docs/install.md
=> updates docs for deb install with apt-secure

codescan/schema.go, codescan/schema_test.go, fixtures/goparsing/classification/models/nomodel.go
support json tag with no name and string tag
=> support json tag with no name

codescan/application.go
Fixes https://github.com/go-swagger/go-swagger/issues/2122
=> fix endless loop issue for pkg import analysis

docs/guidelines/README.md
=> fix(doc): updated contributing guidelines

docs/faq/faq_model.md
=> fix(doc): fixed broken link in models FAQ

fixtures/enhancements/2167/swagger-error.yml, fixtures/enhancements/2167/swagger.yml, generator/operation.go, generator/parameter_test.go, generator/urlbuilder_test.go
=> feat(parameters): query & path parameters now accept x-go-name

codescan/parameters.go
=> ignore not exported params fields

hack/codegen-fixtures.yaml, hack/codegen_nonreg_test.go
* CI codegen: fixed codegen failures on fixtures not producing models
* CI codegen: added filter to exclude specs from test job
=> CI codegen

docs/tutorial/custom-server.md
fix some typo I find in custom-server.md  
It is my first commit for  Open Source, I feel exicted for that. My English is not good,  If I make a wrong bug fix, please forgive me  Thanks
=> fix some typo I find in custom-server.md  

scan/parameters.go, scan/responses.go, scan/scanner.go
=> #2199 Remove the duplicate `withEnum` functions inside `scan` package

docs/generate/spec.md
#2270 
Signed-off-by: glindsell <gl@seldon.io>
=> Update docs for spec generation

cmd/swagger/commands/diff.go, cmd/swagger/commands/expand.go, cmd/swagger/commands/generate/shared_test.go, cmd/swagger/commands/generate/spec_go111.go, cmd/swagger/commands/mixin.go, cmd/swagger/commands/serve.go, cmd/swagger/commands/validate.go, cmd/swagger/swagger.go, codescan/schema.go, generator/model.go, generator/shared.go, generator/template_repo.go
Rescanned repo and fix linting issues.
=> Fix linting again

fixtures/bugs/2306/fixture-2306.json, generator/model.go, generator/operation.go, generator/operation_test.go, generator/parameter_test.go, hack/codegen-fixtures.yaml
=> more aggressive name deconflicting for inline (anonymous) models generated in the operations package

generator/build_test.go, generator/client_test.go, generator/debug_test.go, generator/discriminators_test.go, generator/enum_test.go, generator/moreschemavalidation_test.go, generator/operation_test.go, generator/pointer_test.go, generator/response_test.go, generator/schemavalidation_test.go, generator/server_test.go, generator/support_test.go, generator/typeresolver_test.go, generator/urlbuilder_test.go
* this commit only affects test files
* it replaces the "if assert.xxx { ... }" pattern by "require.xxx", which simplifies the control flow of tests
NOTE: there are some more to process along the same line...
=> refactored generator tests for readability

README.md
=> Fix VMware reference.

fixtures/bugs/2364/fixture-2364.yaml, generator/model.go, generator/moreschemavalidation_fixtures_test.go, generator/moreschemavalidation_test.go, generator/types.go
=> allow x-nullable hint to override allOf nullability status

cmd/swagger/commands/mixin.go, cmd/swagger/commands/mixin_test.go
Signed-off-by: Stijn De Haes <stijndehaes@gmail.com>
=> Added support to ignore conflicts in mixin command

docs/usage/swagger.md
fix https://goswagger.io/usage/swagger.html
=> doc: fix issue of displaying code

codescan/application.go, scan/classifier.go
Fix https://github.com/go-swagger/go-swagger/issues/2391
=> Fix 2391: Add more infomation to classify error

codescan/responses.go, examples/generated/swagger.json
Under current master, I run ``generate spec`` under ``example/generated`` with error:
``
➜  generated git:(master) go run github.com/go-swagger/go-swagger/cmd/swagger generate spec -o ./swagger.json --scan-models
unknown field type ele for "body"
exit status 1
``
Is this is one bug? And should we fix it?
=> fix codescan, and support SelectorExpr with response.

fixtures/goparsing/spec/api_spec.json, fixtures/goparsing/spec/api_spec.yml, fixtures/goparsing/spec/api_spec_go111.json, fixtures/goparsing/spec/api_spec_go111.yml, go.mod, go.sum
=> fixup replace clause left in go.mod

fixtures/bugs/2330/.gitignore, fixtures/bugs/2330/fixture-2330.yaml, fixtures/bugs/2330/gen-fixtures.sh, hack/codegen-fixtures.yaml
(re breaking changes in go-openapi/validate, go-openapi/errors)
* fixes #2330 (acknowledged by running fixture build)
=> Acknowledged codegen regression fixed

examples/2.0/petstore/README.md, examples/2.0/petstore/server/petstore.go
=> fixed doc in petstore example

.circleci/config.yml
=> Removed redundant unit tests from CI

docs/install.md
see https://unix.stackexchange.com/questions/303669/trying-to-use-pwd-inside-an-alias-giving-unexpected-results
=> fix: use single quotes for pwd in alias

cmd/swagger/commands/generate/spec.go, cmd/swagger/commands/generate/spec_go111.go, cmd/swagger/completion/swagger.zsh-completion, docs/generate/spec.md
Fixes https://github.com/go-swagger/go-swagger/issues/2101
This just tripped me up in the same way.
=> Fix input swagger file docs for spec generation

docs/install.md
Debian install needs sudo apt.
=> added sudo to debian install

generator/language.go, generator/language_test.go
=> generator: fix initialization of empty arrays

codescan/application.go, codescan/application_test.go, codescan/enum.go, codescan/parameters.go, codescan/parser.go, codescan/responses.go, codescan/schema.go
Add the enum description to the generated swagger doc, it's useful when the enum is integer.
=> add enum description

Dockerfile.alpine.ci, Dockerfile.ci, Dockerfile.dev, go.mod
=> update build containers to freeze to go 1.15 for now

.circleci/config.yml, .goreleaser.yml
Added build support for ppc64le architecture
=> Added ppc64le support on circleci & goreleaser

fixtures/bugs/2216/defs.yml, fixtures/bugs/2216/swagger-single.yml, fixtures/bugs/2216/swagger.yml, generator/spec.go, generator/spec_test.go
=> Fix generate server with flag --keep-spec-order

cmd/swagger/commands/serve.go
Gives developers option to host the docs at different uri paths
=> add option to add your own path

.circleci/config.yml
=> build binaries for Darwin arm64

codescan/schema.go
This PR gives support to key non-string in map if the key implements TextMarshaler
=> support key non-string in map if the key implements TextMarshaler interface

examples/todo-list-strict/README.md, examples/todo-list/README.md
=> Update the option --tls-certificate-key to --tls-key of todo-list-server in todo-list example

generator/templates/cli/retrieveflag.gotmpl
fixes #2735
Signed-off-by: Kevin Barbour <kevinbarbourd@gmail.com>
=> Fix issue assigning slice pointer to slice in CLI

codescan/schema.go, codescan/schema_test.go, fixtures/goparsing/classification/models/extranomodel.go
=> support swagger:type on structs

generator/parameter_test.go, generator/templates/server/parameter.gotmpl
Signed-off-by: Nick Dimov <3619341+dimovnike@users.noreply.github.com>
=> #2748 passing request context to ConextValidate()

.github/workflows/test.yaml, .gitignore, .goreleaser.yml, Dockerfile, codescan/parser_go119_test.go, codescan/parser_helpers.go, codescan/parser_helpers_go118.go, codescan/schema_go118_test.go, fixtures/goparsing/classification/models/order.go, fixtures/goparsing/classification/models/order_go118.go, fixtures/goparsing/go118/nomodel.go, generator/helpers_go118_test.go, generator/helpers_test.go, go.sum, hack/download-stats.go, nfpm.yaml
=> Allow older go

.github/workflows/test.yaml, .goreleaser.yml, README.md, cmd/swagger/commands/expand.go, go.mod, go.sum
=> format output as yaml

docs/use/spec/ignore.md
#2311 addressed as part of this PR.
=> swager: ignore documentation.

cmd/swagger/commands/diff/spec_analyser.go, cmd/swagger/commands/generate/model.go, examples/auto-configure/implementation/configure_impl.go, generator/types.go
Fixed some misspells in comments, log messages, and descriptions.
=> Fix some misspells

generator/templates/cli/operation.gotmpl
Fix parameters order when using streaming response (ie, with files).
=> Fix parameters order

generator/templates/client/parameter.gotmpl
=> Fixed generation SetDefaults for client when x-go-name is specified

cmd/swagger/commands/diff/compatibility.go, cmd/swagger/commands/diff/difftypes.go, cmd/swagger/commands/diff/spec_analyser.go, cmd/swagger/commands/diff/spec_difference.go, cmd/swagger/commands/diff_test.go, fixtures/diff/reqparam.diff.breaking.txt, fixtures/diff/reqparam.diff.txt, fixtures/diff/reqparam.v1.json, fixtures/diff/reqparam.v2.json, go.sum
Fixes #2929 and some more fixes
=> fix(diff): swagger diff is not working for certain cases 

fixtures/bugs/2945/fixture-2945.yaml, generator/client_test.go, generator/templates/client/response.gotmpl
=> Use proper operation name in default client error

generator/templates/server/server.gotmpl
=> Fix default write timeout value from 60s to 30s in Server struct

examples/contributed-templates/stratoscale/restapi/configure_petstore.go, generator/templates/contrib/stratoscale/README.md, generator/templates/contrib/stratoscale/server/configureapi.gotmpl
This PR cherry-picks the commit from @fivitti in PR #2796, and resolves merge conflict. Did not regenerate examples to avoid more conflicts. Examples will be regenerated altogether in a follow-up PR.
=> Use mockery V2 argument style

cmd/swagger/commands/flatten_test.go, cmd/swagger/commands/generate/shared.go, docs/usage/flatten.md, fixtures/bugs/2334/bar.yaml, fixtures/bugs/2334/swagger.yaml
=> fix(flatten): added option to flatten without transforming names

generator/client_test.go, generator/templates/client/response.gotmpl
* missed a guard when response is a stream
* corrected white space
=> fix: follow-up on #3019 - fixed templates

examples/tutorials/custom-server/README.md
=> doc(example): fixed doc for custom-server example

docs/faq/faq_documenting.md
documentation update with regards to this [#2401](https://github.com/go-swagger/go-swagger/issues/2401)
=> fix(faq): updating doc to get swagger UI

.codecov.yml
Excludes examples and fixtures from code coverage.
=> ci: fixed test coverage computation

Dockerfile
=> reduce docker images size

.github/workflows/test.yaml, .golangci.yml, codescan/routes_test.go, generator/language_test.go, generator/media_test.go, generator/model_test.go
=> fix linter issues & upd linter settings/action 

docs/install/install-source.md
=> Improve docs

docs/faq/faq_server.md
=> doc: fixed reference to incorrect flag --skip-main
